### ISSUE TITLE
Satellite UI / Invited users should not be able to change limits

### ISSUE THREAD

**Issue by boshevski** [storj/storj#6215] opened 2023-08-25 10:07 UTC
Only owners should be able to change limits, not members invited to a project.

**Comment by VitaliiShpital** [comment] 2023-08-28 11:03
this is a duplicate of some ticket.

It was fixed by @wilfred-asomanii with this change
https://review.dev.storj.io/c/storj/storj/+/10651

**Closed** 2023-08-28 11:04 UTC
Labels: Bug, Satellite UI
