### ISSUE TITLE
Notification about new software version available is missing in the dashboard

### ISSUE THREAD

**Issue by MaxMaximus** [storj/storj#3906] opened 2020-06-07 19:38 UTC
Hello. 
Looks like you "overfix" previous issue #3865 in ver. 1.3.3 about new version notification asking for software  update shown up in the SNO Dashboard too early (before ver  is rolled out to a particular node and so not actually available for an update)

Now there are no any update notification in the node dashboard even after new version is available and already "rolled out" to a particular node. I still run 3 nodes on v 1.3.3. and got no any notifications in the DashBoard after 1.4.2 and 1.5.2 were released. (Although i have got message about outdated version via operator email from Storj server)

**Comment by MaxMaximus** [comment] 2020-06-13 06:03
Also i just noticed that one of these 1.3.3 nodes does not want to update saying "new version is available, but not rolled-out to your node-ID".
You really still want to hold some nodes on 1.3.3 or it is an another bug?

**Comment by ifraixedes** [comment] 2020-06-15 13:18
yes, it looks a bug.

**Comment by MaxMaximus** [comment] 2020-06-16 02:41
One node got an updated today without any changes on my side. Look like a have figured out that is happening.  I have open a new issue for it.  
Node which got an update still did not show notification in dashboard about running outdated version so i think this issues not related.

**Comment by stefanbenten** [comment] 2020-06-16 11:29
@ifraixedes @MaxMaximus This is not a bug, the notification system on the SN Dashboard was disabled with this commit: https://github.com/storj/storj/commit/0f71e60a53376bd0b367ae8640f3eabe32ce2ad9

It has not been enabled since then. Besides that your Node is not eligble for the last rollout yet as you mentioned in #3909 .

**Comment by ifraixedes** [comment] 2020-06-16 13:03
@stefanbenten the bug that I was referring was about that the node was stuck on `v1.3.3` we rolled out 3 versions since that one, but the last one doesn't count because we stopped the roll out at 80% as you know, so why @MaxMaximus node didn't get updated to `v1.4.2` or `v1.5.2`?

**Comment by ifraixedes** [comment] 2020-06-16 13:06
Oh, I've just seen #3909 that it's describing the bug that I was referring, however at that time that issue didn't exist.

**Comment by ifraixedes** [comment] 2020-06-16 13:07
Should we close this issue as the notification was disabled intentionally and we have #3909 for the nodes getting stuck on an old version?

**Comment by Qweder93** [comment] 2020-07-14 12:27
https://review.dev.storj.io/c/storj/storj/+/2143
done, will be in next release

**Closed** 2020-07-14 12:27 UTC
Labels: Bug, Tracked in Jira
