### ISSUE TITLE
The storagenode do not respect the limit for disk allocation

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/storj#1755] opened 2019-04-13 16:59 UTC
The storage node operator used 100 GB as allocated space.
At the moment, Storagenode has 166GB and continues to grow.
See https://docs.storj.io/discuss/5cb20f73027ebc0024b971d8 for reference.

**Comment by MqllR** [comment] 2019-04-14 07:19
Same issue:

```
Disk     -21849170944 B     291.8 GB
```

**Comment by BlackDuck888** [comment] 2019-04-16 08:00
Same to me @501GB now i have 506GB

And in Rocketchat others report same 
https://community.storj.io/channel/storagenode?msg=iHxgx49NQW4DZe9qE

**Comment by therealmko** [comment] 2019-04-16 08:27
I can confirm too, 500GB allocated, 503GB occupied and growing:

                       Available         Used     Egress      Ingress
     Bandwidth            1.5 TB     516.0 GB     4.5 GB     511.5 GB (since Apr 1)
          Disk     -3615792128 B     503.6 GB

**Comment by ReneSmeekes** [comment] 2019-04-24 16:28
I've seen at least one user who accidentally set the bandwidth to 200MB have the same issue with bandwidth. Should that be a separate issue?

**Comment by Storjeez** [comment] 2019-04-25 20:38
This seems to be fixed with the latest version. Overfixed.

**Comment by stefanbenten** [comment] 2019-04-28 05:31
Closing in favor of new exisiting issue: #1839

**Closed by stefanbenten** 2019-04-28 05:31 UTC
