### ISSUE TITLE
Satellite needs to keep track of correct auth service endpoint by account type

### ISSUE THREAD

**Issue by jtolio** [storj/storj#6190] opened 2023-08-17 15:50 UTC
I guess we need to add a field to the project table? If the field is null we use the Satellite default. If the field is not null we use that field's value. We will need fields for both authservice, internal linksharing, and public linksharing. Authservice says which gateway to use so we don't need to set the gateway URL anywhere.

**Comment by onionjake** [comment] 2023-08-28 20:14
Placement annotations have been added that can be used instead of adding a database column.

**Comment by onionjake** [comment] 2023-08-28 20:31
Related: https://github.com/storj/storj-private/issues/408

**Comment by onionjake** [comment] 2023-08-28 20:38
It makes sense to all annotate with the URL's that are needed on each placement? Then we don't need to code in a url "template" somewhere else in the code.

So something like `annotate("edge-url","s3.us-select-1.storjapi.io") && annotate("edge-auth-url","auth.us-select-1.storjapi.io")`

**Comment by ferristocrat** [comment] 2023-08-29 05:03
### Overview

**Comment by ferristocrat** [comment] 2023-08-29 05:18
@jtolio - is the above accurate? If we're able to use placements, the only work is on the [Satellite UI side](https://github.com/storj/storj/issues/6188) (and uplink) right?

**Comment by jtolio** [comment] 2023-09-05 16:51
We don't need gateway-url since the authservice tells clients what gateway url to use.

We do need auth url and public linksharing url and internal linksharing url yeah. We will need to add those annotations to the placement config, and we will need a Satellite-side method that will return those annotations. We don't currently have a way for the UI or the uplink to learn about those annotations, so that endpoint will have to be a part of this. But that should be very small effort.

**Comment by jtolio** [comment] 2023-09-05 16:56
https://review.dev.storj.io/c/storj/storj/+/11094 looks like it completely does everything i hoped for by filing this ticket. nice job @jewharton

**Comment by NiaStorj** [comment] 2023-09-06 13:48
close because it'a a dupe of https://github.com/storj/infra/issues/4764

**Comment by jtolio** [comment] 2023-09-06 13:53
It actually wasn't a dupe - storj/infra#4764 is the configuration step, this ticket tracks the satellite code plumbing to make that configuration do something, and 6188 is the change that uses the plumbing from this ticket. once https://review.dev.storj.io/c/storj/storj/+/11094 is merged, then this ticket will be done

**Closed** 2023-09-12 18:01 UTC
Labels: Needs Estimation, Needs Grooming
