### ISSUE TITLE
It would be nice if the IP Address was detected.

### ISSUE THREAD

**Issue by sixcorners** [storj/storj#3923] opened 2020-07-20 11:40 UTC
It would be nice if I didn't have to have a different configuration per node to set the advertised IP address or set the entrypoint/command to look up that information. It's good to be able to set it manually but usually the IP the node contacted the satellite with is the correct IP to use. If the IP turns out to be something that changes the software would be in the best position to fix it when it does.

**Comment by stefanbenten** [comment] 2020-07-20 12:44
Hey @sixcorners ,

I do not see where the issue/advantage is. We should not try to make an IP updater in our software (that’s not the expertise and purpose of it).
An good example is the actual DDNS address that we recommend to add/use. Furthermore the port of a node has to change anyway, if ran within the same network as others (behind your firewall/router). For that reason, I do not believe that striping this out and trying to automatically do this, is a good idea.

**Comment by sixcorners** [comment] 2020-07-24 08:30
If you manage multiple machines with different IP addresses then the port doesn't have to change. I think it's actually recommended to not run multiple nodes behind the same IP since they get treated as the same node for purposes of selecting a node to upload a file to and for auditing.
Anyway, if this was implemented it would allow me to have one config for a cluster of servers. I don't know what that is worth.

**Comment by stefanbenten** [comment] 2020-07-24 08:48
You might want to use Environment variables in this case. That would serve your needs.
Lemme know if you need help with that!

**Comment by sixcorners** [comment] 2020-07-26 05:51
Ok environment variables...
```
version: "3.7"
services:
  storjnode:
    image: storjlabs/storagenode:beta
    restart: unless-stopped
    deploy:
      mode: global
      stop_grace_period: 5m
    environment:
      - WALLET=0xxxxxx
      - EMAIL=xxxxx
      - ADDRESS=${HOST_IPV4}:28967
      - STORAGE=500GB
    volumes:
      - storj-identity:/app/identity
      - storj-storage:/app/config
    ports:
      - 28967:28967
volumes:
  storj-identity:
  storj-storage:
```
I deployed this on my swarm cluster. Now I have 3 storj nodes that are all reporting the same ip address. What do I do now?

**Comment by sixcorners** [comment] 2020-08-08 13:58
Ya I don't think this is possible. I think the environment variable thing is not workable.

**Comment by Doom4535** [comment] 2021-02-25 05:30
This would be a great optional feature to have from the SNO side.  The SNO sets a flag that they desire this behavior, and the satellite will use the last known IP address of the storage node as the downlink address.  This approach could also be extended to include the port number as well.

To ensure that the connection is properly maintained, the storage node will need to dial in periodically if it has no traffic.

To further extend this, [UDP hole punching](https://en.m.wikipedia.org/wiki/UDP_hole_punching) could be employed.  This would remove the need for the SNO to even forward ports in most cases.

**Comment by drewwells** [comment] 2021-04-20 14:19
I'm not familiar enough with the inner workings of service discovery in Storj. I see there's a heartbeat happening in the network that periodically pings my machine and my client updates state on this. The idea of registering multiple ports on the same IP is not an ideal idea. It's much preferable that the nodes are available on only a single port.

Most systems I have experience with do health checks in reverse. Let's take Kubernetes as an example. The control plane does not contact all the nodes, instead the control plane is available on a specific DNS/IP address. The nodes (kubelet) contact this address periodically to update state. As such, kubelet does not need an IP address for this functionality. The obvious question here is how do you then contact kubelet. When kubelet registers with the control plane, it also reports an IP address. Kubelet registers itself in the same way that storj does by requiring each SNO have an available DNS/IP to contact the node on.

This is definitely a limitation in both scenarios, but it is not a stretch of the imagination to consider how this problem can be flipped. If node (kubelet) connects to a centralized location and registers a port there say 127.0.0.1:32007. Now this location can be advertised as a relay location to contact the node. You could even use this channel just to relay messages to the storage node. Take as example

1. user uploads a payload to us1
2. my node is relaying in us2
3. us1 looks up node on us2 and requests node to make a port available in us1 region
4. node registers a reverse tunnel in us1 and we ship payload over this channel

The process of registering reverse tunnels is trivial. The technology gap here that I see is a distributed service discovery to contact all these IP-less nodes. I used this at Oracle Kubernetes Engine to register kubelets that did not have public IP addresses and were not in the same VPC as the control plane. It was a managed service, so customer ndoes were in separate networks from the control plane.

**Comment by thepaul** [comment] 2021-04-20 23:57
> It's much preferable that the nodes are available on only a single port.

Nodes are available on only a single port. We don't store multiple ports per node. All incoming requests from the storj network to a given node will come in on the same port.

It's not entirely clear what problem you are attempting to solve, here, with the reverse tunnels and the k8s. It doesn't seem to be related to detecting the IP address. Are you suggesting a form of NAT hole punching, to make network setup easier? If so, that is indeed on the roadmap, but we will want to implement it in a way that does not significantly increase the latency of uplink->node connections (waiting for a reverse tunnel to be established would do that).

**Comment by drewwells** [comment] 2021-04-21 18:22
The issue to me is not about the program being able to detect an IP address. The issue is that a unique IP address is required for each node to participate. Is the road map viewable somewhere?

**Comment by thepaul** [comment] 2021-04-22 14:40
> The issue is that a unique IP address is required for each node to participate.

That is not the case. Nodes only need a unique IP+port combination.

> Is the road map viewable somewhere?

I only meant that we have been doing research toward that end and that we are planning on addressing it, but I don't think it has been added to any 'official' roadmaps. This is a good place to start for the official direction: https://www.storj.io/blog/product-development-update-april-2021

**Comment by iglesiasbrandon** [comment] 2024-02-22 17:37
Closing this issue for now as won't fix.

**Closed by iglesiasbrandon** 2024-02-22 17:37 UTC
Labels: wontfix, SNO
