### ISSUE TITLE
PUT_REPAIR Unexpected EOF

### ISSUE THREAD

**Issue by stanfieldr** [storj/storj#2492] opened 2019-07-09 05:35 UTC
I'm not sure if this is any help to yall, but I noticed it while browsing the logs :eyes:

```
2019-07-09T05:06:24.368Z	INFO	running on version v0.14.3
2019-07-09T05:06:41.235Z	INFO	piecestore	upload started	{"Piece ID": "QXXN6B4DKH2KEGBUIVMD5DS2MKX74GZ25XSLD2OEI3VPLQRYP5SA", "SatelliteID": "12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs", "Action": "PUT_REPAIR"}
2019-07-09T05:06:53.558Z	INFO	piecestore	upload failed	{"Piece ID": "QXXN6B4DKH2KEGBUIVMD5DS2MKX74GZ25XSLD2OEI3VPLQRYP5SA", "SatelliteID": "12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs", "Action": "PUT_REPAIR", "error": "piecestore protocol: unexpected EOF", "errorVerbose": "piecestore protocol: unexpected EOF\n\tstorj.io/storj/storagenode/piecestore.(*Endpoint).Upload:222\n\tstorj.io/storj/pkg/pb._Piecestore_Upload_Handler:602\n\tstorj.io/storj/pkg/server.logOnErrorStreamInterceptor:23\n\tgoogle.golang.org/grpc.(*Server).processStreamingRPC:1209\n\tgoogle.golang.org/grpc.(*Server).handleStream:1282\n\tgoogle.golang.org/grpc.(*Server).serveStreams.func1.1:717"}
2019-07-09T05:06:53.558Z	ERROR	piecestore protocol: unexpected EOF
	storj.io/storj/storagenode/piecestore.(*Endpoint).Upload:222
	storj.io/storj/pkg/pb._Piecestore_Upload_Handler:602
	storj.io/storj/pkg/server.logOnErrorStreamInterceptor:23
	google.golang.org/grpc.(*Server).processStreamingRPC:1209
	google.golang.org/grpc.(*Server).handleStream:1282
	google.golang.org/grpc.(*Server).serveStreams.func1.1:717
```

**Comment by ifraixedes** [comment] 2019-07-10 00:28
@stanfieldr thanks for reporting it.

We are aware of these `EOF` errors the are due to the connection is closed by any of the sides, but unfortunately we don't have so far more information about the cause of them. 

We have in our backlog to add more information to the log messages for knowing more about all the different causes and provide a specific message.

**Closed by ifraixedes** 2019-07-10 00:28 UTC
