### ISSUE TITLE
Satellite UI / Upgrade notification

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5481] opened 2023-01-17 15:35 UTC
Replace the blue upgrade notification on top with the new design of notifications.
Show only on the dashboard page.
Show after a week, not immediately after signup.

Figma:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=15026%3A107362&t=Mk9KCJUMRPWNVeCb-0

Old notification:
![Image](https://user-images.githubusercontent.com/3217669/212941263-0c8135ab-454b-473d-b6b2-8825f810a371.png)

New notification:
![Image](https://user-images.githubusercontent.com/3217669/212941494-877c1b8a-2a98-48cb-af90-a53973dd56f2.png)

**Comment by mobyvb** [comment] 2023-02-08 15:03
duplicate of https://github.com/storj/storj/issues/5525?

**Comment by boshevski** [comment] 2023-02-08 17:14
Yes

**Closed** 2023-02-08 22:30 UTC
Labels: Satellite UI
