### ISSUE TITLE
Repair worker consuming 12% of the DB resources for updating reputation

### ISSUE THREAD

**Issue by nadimhq** [storj/storj#4939] opened 2022-06-28 12:41 UTC
![Jun23-Jun28retries](https://user-images.githubusercontent.com/82845192/176180717-5216a5fb-e2aa-4698-997c-25a4436f2f93.JPG)

This doesn't scale down the line since more data would equal more repair workers

![image](https://user-images.githubusercontent.com/82845192/176182417-e7aa3e51-29d9-4fdb-8319-68d4c018dd0e.png)

**Comment by littleskunk** [comment] 2022-06-28 13:10
The reason we created an issue for this is that we expect an emergency somewhere in the future. At the moment the repair worker consumes 12% of the DB resources to update the storage node reputation. The more data the satellite is holding the more work the repair worker will get and that will increase the resource consumption on the database. So let's file a ticket to fix this issue while it is cheap to fix without an emergency.

The reason this update query is so expensive has to do with the way repair workers work. We are running multiple repair workers on different machines. Each repair task usually ends with a list of 29 reputation updates. The problem is that multiple repair workers want to update the reputation of the same nodes. That causes a high number of retries.

As far as I know, the plan was to batch the reputation updates. I don't believe that will change much because it only batches the reputation updates per repair worker. Multiple repair workers would still fire multiple update batches at the same time. These concurrent batches would still try to update the same nodeIDs. That will cause a high number of retries. We might be able to scale a bit higher without batches but I would still expect an emergency at the end.

My first idea to fix this issue was to disable the feature flag. It turns out we have a feature flag in the config but it was removed from the code. Even if everyone in the company believes this is not a problem can we at least bring back the feature flag? If I get paged in the middle of the night I want to be able to fix the issue with a simple config change.

My second idea is more about a long-term solution. If all repair workers would share the same reputation cache we could batch the audit updates in a way that guarantees almost no retries (for 0 retries the audit job would need to use the same reputation cache). That is maybe a bit too complicated to implement. Another solution would be to run the reputation updates just on a single repair worker. That would also reduce the number of retries but still give us some spot checks. There might be some other way to run spot checks. My point here is that a spot check would cut down the number of updates while still incentivising cheaters to not start gaming us.

**Comment by ifraixedes** [comment] 2022-06-28 13:36
> f all repair workers would share the same reputation cache we could batch the audit updates in a way that guarantees almost no retries (for 0 retries the audit job would need to use the same reputation cache). That is maybe a bit too complicated to implement.

My understanding is that should be a global cache for all the repair workers so we need some system like Redis.

Assuming that I understood correctly, we should evaluate if we want to maintain that caching system and the cost of it.

I guess that this is a good topic to expose in a dev guild arch meeting and probably draft a blueprint.

**Comment by thepaul** [comment] 2022-08-11 15:29
+1 on adding back the feature flag.

Also, having only one repair worker update reputation is a great idea, let's do that. We can scale the number of repair workers that update reputation up and down however we like, getting a tradeoff between resources and better reliability information.

**Comment by thepaul** [comment] 2022-08-18 14:46
I've just opened #5089 to address the feature flag change. Should we keep this ticket for the larger "we need to make a blueprint for consuming all reputation info" problem, or would you like a new ticket for that?

**Comment by thepaul** [comment] 2022-12-06 16:09
Close it.

**Comment by iglesiasbrandon** [comment] 2023-03-17 15:05
closing (3 months later heh)

**Closed by iglesiasbrandon** 2023-03-17 15:05 UTC
Labels: Bug, Needs Estimation
