### ISSUE TITLE
Block IO usage out of proportion with Net IO in v0.15.3

### ISSUE THREAD

**Issue by nathandragun** [storj/storj#2619] opened 2019-07-22 21:12 UTC
When monitoring resource usage through `docker stats --all` I noticed that the Block I/O traffic seemed to be greatly out of proportion with Net I/O.  1st output:

![disk IO](https://user-images.githubusercontent.com/40903109/61664743-712d0a00-aca1-11e9-8a3d-91309f888369.PNG)

After approximately 40 minutes I took another sample.  2nd output:

![disk IO 2](https://user-images.githubusercontent.com/40903109/61664798-8dc94200-aca1-11e9-9e16-48fc63e09ed7.PNG)

1) During the two periods in question Net inbound grew by 4GB while Block outbound grew by 7GB.  This seems to imply that for every 4GB of data received, 7GB of Block outbound operations are necessary.  Unless some form of hashing integrity check is taking place for every completed piece, it appears that there may be an excess of disk operations taking place.

2) Strangely enough we seem to have a Net outbound of 41.2GB, in the first sample, yet Block inbound only 2.02GB.  I can see this making sense during the testing period if a) the pieces are being stored in memory, and b) the same pieces keep being requested.

Node details:
OS: Ubuntu 18.04.02 LTS
Docker version 18.09.7, build 2d0083d
Uptime: 22h13m22s~
Bandwith: 637.3TB / 2.7TB / 1.0TB / 1.7TB
Disk: 17.7TB / 278.7GB

**Comment by modemboy** [comment] 2019-07-23 02:06
Likely OS disk caching and double counting of writes, as per: https://www.n0r1sk.com/post/docker-block-i-o-and-the-black-hole/

Don't rely on docker stats for accurate reporting. 
Likely not a bug.

**Comment by nathandragun** [comment] 2019-07-23 03:18
> Likely OS disk caching and double counting of writes, as per: https://www.n0r1sk.com/post/docker-block-i-o-and-the-black-hole/
> 
> Don't rely on docker stats for accurate reporting.
> Likely not a bug.

Unfortunately this link refers to issues with NFS Block IO reporting only.  As the results provided above utilize directly attached storage it does not suffer from the issue the article linked talks about.

**Comment by modemboy** [comment] 2019-07-23 15:37
> Unfortunately this link refers to issues with NFS Block IO reporting only. As the results provided above utilize directly attached storage it does not suffer from the issue the article linked talks about.

Unfortunately you only looked at the first part and ignored the entire section titled:
Finding 2: docker stats tracks block I/O not fully correct
about how the writes are double counted (nothing to do with NFS).

Regardless if that's the source of the issue or not, docker stats is not showing what you think it's showing, and this is not an issue.

**Comment by stefanbenten** [comment] 2019-11-24 16:20
I am going to close this ticket, as this is not an issue due to our software as mentioned in the comments above.

**Closed by stefanbenten** 2019-11-24 16:20 UTC
