### ISSUE TITLE
uplink cp folder / recursive

### ISSUE THREAD

**Issue by kallisti5** [storj/storj#4542] opened 2022-02-17 16:27 UTC
Are there any plans to recursively upload folders with uplink?
Seems like an extremely basic task that is seemingly unsupported :-)

```
uplink cp ./haiku-release sj://haiku-release/
Error: source cannot be a directory: /s3/haiku-release
```

**Comment by mniewrzal** [comment] 2022-02-17 16:35
Please try `uplinkng` binary from https://github.com/storj/storj/releases/tag/v1.48.2. Just remember to add `--recursive` flag.
We plan to replace the current `uplink` binary with `uplinkng` soon.

**Comment by kallisti5** [comment] 2022-02-17 16:50
uplinkng seems to be a lot more complete :-)

Seeing some oddities though... I guess they're better reserved for another issue though.

```
# uplinkng cp --progress -r /s3/haiku-release sj://haiku-release/
upload /s3/haiku-release/README to sj://haiku-release/README
upload /s3/haiku-release/r1alpha1/haiku-r1alpha1-image.zip to sj://haiku-release/r1alpha1/haiku-r1alpha1-image.zip
upload failed: uplink: stream: ecclient: successful puts (42) less than success threshold (80); uplink: stream: ecclient: successful puts (49) less than success threshold (80); uplink: stream: ecclient: successful puts (44) less than success threshold (80)
upload /s3/haiku-release/r1alpha1/haiku-r1alpha1-image.zip.torrent to sj://haiku-release/r1alpha1/haiku-r1alpha1-image.zip.torrent
upload /s3/haiku-release/r1alpha1/haiku-r1alpha1-iso.zip to sj://haiku-release/r1alpha1/haiku-r1alpha1-iso.zip
```

**Comment by mniewrzal** [comment] 2022-02-17 16:55
hmm could you try flag `--parallelism 1`?

**Comment by kallisti5** [comment] 2022-02-17 18:02
parallelism 1 definitely makes it more reliable..

```
upload /s3/haiku-release/r1alpha2/haiku-r1alpha2-anyboot.tar.xz to sj://haiku-release/r1alpha2/haiku-r1alpha2-anyboot.tar.xz
upload failed: uplink: stream: ecclient: successful puts (73) less than success threshold (80); uplink: stream: ecclient: successful puts (75) less than success threshold (80)
upload /s3/haiku-release/r1alpha2/haiku-r1alpha2-anyboot.torrent to sj://haiku-release/r1alpha2/haiku-r1alpha2-anyboot.torrent
upload /s3/haiku-release/r1alpha2/haiku-r1alpha2-anyboot.zip to sj://haiku-release/r1alpha2/haiku-r1alpha2-anyboot.zip
upload failed: uplink: stream: ecclient: successful puts (58) less than success threshold (80); uplink: stream: ecclient: successful puts (44) less than success threshold (80); uplink: stream: ecclient: successful puts (42) less than success threshold (80); uplink: stream: ecclient: successful puts (41) less than success threshold (80)
upload /s3/haiku-release/r1alpha2/haiku-r1alpha2-image.tar.xz to sj://haiku-release/r1alpha2/haiku-r1alpha2-image.tar.xz
upload failed: uplink: stream: ecclient: successful puts (74) less than success threshold (80); uplink: stream: ecclient: successful puts (78) less than success threshold (80)
upload /s3/haiku-release/r1alpha2/haiku-r1alpha2-image.zip to sj://haiku-release/r1alpha2/haiku-r1alpha2-image.zip
upload failed: uplink: stream: ecclient: successful puts (53) less than success threshold (80); uplink: stream: ecclient: successful puts (42) less than success threshold (80); uplink: stream: ecclient: successful puts (49) less than success threshold (80); uplink: stream: ecclient: successful puts (36) less than success threshold (80)
upload /s3/haiku-release/r1alpha2/haiku-r1alpha2-iso-sources.tar.xz to sj://haiku-release/r1alpha2/haiku-r1alpha2-iso-sources.tar.xz


^C
[root@ipfspri ~]# uplinkng cp --parallelism 1 --progress -r /s3/haiku-release sj://haiku-release/
upload /s3/haiku-release/README to sj://haiku-release/README
upload /s3/haiku-release/r1alpha1/haiku-r1alpha1-image.zip to sj://haiku-release/r1alpha1/haiku-r1alpha1-image.zip
upload /s3/haiku-release/r1alpha1/haiku-r1alpha1-image.zip.torrent to sj://haiku-release/r1alpha1/haiku-r1alpha1-image.zip.torrent
upload /s3/haiku-release/r1alpha1/haiku-r1alpha1-iso.zip to sj://haiku-release/r1alpha1/haiku-r1alpha1-iso.zip
upload /s3/haiku-release/r1alpha1/haiku-r1alpha1-iso.zip.torrent to sj://haiku-release/r1alpha1/haiku-r1alpha1-iso.zip.torrent                                          
upload /s3/haiku-release/r1alpha1/haiku-r1alpha1-vmdk.zip to sj://haiku-release/r1alpha1/haiku-r1alpha1-vmdk.zip
upload /s3/haiku-release/r1alpha1/haiku-r1alpha1-vmdk.zip.torrent to sj://haiku-release/r1alpha1/haiku-r1alpha1-vmdk.zip.torrent                
upload /s3/haiku-release/r1alpha1/md5sum.txt to sj://haiku-release/r1alpha1/md5sum.txt
upload /s3/haiku-release/r1alpha1/sources/Python-2.6.2.tgz to sj://haiku-release/r1alpha1/sources/Python-2.6.2.tgz
upload /s3/haiku-release/r1alpha1/sources/apr-1.3.8-with-haiku-patch.tar.gz to sj://haiku-release/r1alpha1/sources/apr-1.3.8-with-haiku-patch.tar.gz
upload /s3/haiku-release/r1alpha1/sources/apr-util-1.3.9.tar.gz to sj://haiku-release/r1alpha1/sources/apr-util-1.3.9.tar.gz
upload /s3/haiku-release/r1alpha1/sources/autoconf-2.64.tar.gz to sj://haiku-release/r1alpha1/sources/autoconf-2.64.tar.gz
upload /s3/haiku-release/r1alpha1/sources/automake-1.11.tar.gz to sj://haiku-release/r1alpha1/sources/automake-1.11.tar.gz
upload /s3/haiku-release/r1alpha1/sources/bison-2.4.1.tar.gz to sj://haiku-release/r1alpha1/sources/bison-2.4.1.tar.gz
upload /s3/haiku-release/r1alpha1/sources/curl-7.19.6.tar.gz to sj://haiku-release/r1alpha1/sources/curl-7.19.6.tar.gz
upload /s3/haiku-release/r1alpha1/sources/curl-7.19.6.tar.gz.1 to sj://haiku-release/r1alpha1/sources/curl-7.19.6.tar.gz.1
upload /s3/haiku-release/r1alpha1/sources/cvs-1.12.13-with-haiku-patch.tar.gz to sj://haiku-release/r1alpha1/sources/cvs-1.12.13-with-haiku-patch.tar.gz
upload /s3/haiku-release/r1alpha1/sources/cvs-1.12.13-with-haiku-patch.tar.gz.1 to sj://haiku-release/r1alpha1/sources/cvs-1.12.13-with-haiku-patch.tar.gz.1
upload /s3/haiku-release/r1alpha1/sources/expat-2.0.1.tar.gz to sj://haiku-release/r1alpha1/sources/expat-2.0.1.tar.gz
upload /s3/haiku-release/r1alpha1/sources/flex-2.5.35.tar.gz to sj://haiku-release/r1alpha1/sources/flex-2.5.35.tar.gz
upload /s3/haiku-release/r1alpha1/sources/git-1.6.4.2.tar.gz to sj://haiku-release/r1alpha1/sources/git-1.6.4.2.tar.gz
upload /s3/haiku-release/r1alpha1/sources/haiku-r1alpha1-BeZillaBrowser-2.0.0.22pre-2009-09-08.tar.bz2 to sj://haiku-release/r1alpha1/sources/haiku-r1alpha1-BeZillaBrowser-2.0.0.22pre-2009-09-08.tar.bz2
```

**Comment by dcrystalj** [comment] 2022-03-15 23:42
would make sense to add option to auto retry failed uploads

**Comment by Erikvv** [comment] 2022-03-16 09:24
Is it true this error might be caused by https://github.com/storj/storj/issues/4606 ?

**Comment by dcrystalj** [comment] 2022-03-16 09:40
it might be, I am running this in ubuntu. Its annoying to recursively upload folder and if some of files fail you need to manually retry 🤯

**Comment by iglesiasbrandon** [comment] 2024-02-22 18:15
This issue was resolved, closing it.

**Closed by iglesiasbrandon** 2024-02-22 18:15 UTC
