### ISSUE TITLE
Simple view of Revenue Share for Value Attribution

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#5123] opened 2022-08-26 22:56 UTC
We want a simple view calculating the amount of revenue we are sharing with each partner.

AC:
- each user agent is displayed in a table format with total revenue (actually paid from users), we can view this per month 
> _- coupons should already be removed from this total since we are only counting received revenue_
- there is a line item deducting the cost of paying node operators per month, which is 60% of the received revenue 
- we want the ability to see YTD and month to month

**Comment by iglesiasbrandon** [comment] 2022-09-06 19:05
i think this is a duplicate of https://github.com/storj/storj/issues/4956 and https://github.com/storj/datascience/issues/248 and https://github.com/storj/datascience/issues/192

**Comment by iglesiasbrandon** [comment] 2022-09-06 19:07
im going to close this ticket for now since we belive its a duplicate, @stoweandi please open it again if its different. CC @mobyvb @cam-a

**Closed** 2022-09-06 19:08 UTC
Labels: Value Attribution
