### ISSUE TITLE
storagenode version is up to date

### ISSUE THREAD

**Issue by sixcorners** [storj/storj#3865] opened 2020-04-26 08:29 UTC
The updater thinks my storage node is up to date:
"storagenode version is up to date"
My storage node thinks it needs to be updated:
"Update your Node to Version v1.3.3: It's time to update your Node's software, you are running outdated version v1.1.1"
Is this a bug?

**Comment by MaxMaximus** [comment] 2020-04-27 07:36
I see similar issue. Dashboard says i need to update with sending notification messages like this last 3 days:
`Update your Node to Version v1.3.3: It's time to update your Node's software, you are running outdated version v1.1.1` 
But updater service does not want update my node and it stays at ver. 1.1.1. And if i open storagenode-updater.log file there is a reason why this happening:
```
2020-04-27T10:24:15.887+0300	INFO	Downloading versions.	{"Server Address": "https://version.storj.io"}
2020-04-27T10:24:16.634+0300	INFO	New version available but not rolled out to this nodeID yet	{"Service": "storagenode"}
```

**Comment by ifraixedes** [comment] 2020-04-27 13:13
@sixcorners if you see the same message than @MaxMaximus then it's expected behavior. We roll out the versions to Windows SN slowly.

I suppose that we have to fix the dashboard for not sending those notifications or sending them with the explanation that the logs say.

**Comment by ifraixedes** [comment] 2020-04-27 13:32
@sixcorners @MaxMaximus I found out that the bug with the dashboard is fixed. The `v1.1.1` contains the bug but a later version shouldn't.

I'm closing the issue.
Please wait until your nodes get updated to `v1.3.3` and if the issue persists then we'll reopen it.

**Closed by ifraixedes** 2020-04-27 13:32 UTC
Labels: Bug

**Comment by angelsantillana94** [comment] 2020-04-30 10:06
Hello,

I have a similar problem. 
My node is running on version v1.1.1. 
The dashboard displays the following message: "Update your Node to Version v1.3.3: It's time to update your Node's software, you are running outdated version v1.1.1"

My node is running on linux docker (ARM-based platforms)


user@node00:~$ docker logs storagenode 
2020-04-30T09:06:07.471Z	INFO	Configuration loaded from: /app/config/config.yaml
2020-04-30T09:06:07.476Z	INFO	Operator email: xxxx@domain.com
2020-04-30T09:06:07.477Z	INFO	operator wallet: 0xXXXXXXXXXXXXXXXXX
2020-04-30T09:06:08.577Z	INFO	version	running on version v1.1.1
2020-04-30T09:06:08.755Z	INFO	db.migration	Database Version	{"version": 33}
2020-04-30T09:06:09.506Z	INFO	preflight:localtime	start checking local system clock with trusted satellites' system clock.
2020-04-30T09:06:10.443Z	INFO	preflight:localtime	local system clock is in sync with trusted satellites' system clock.
2020-04-30T09:06:10.444Z	INFO	trust	Scheduling next refresh	{"after": "5h7m18.280478937s"}
2020-04-30T09:06:10.444Z	INFO	bandwidth	Performing bandwidth usage rollups
2020-04-30T09:06:10.445Z	INFO	Node 1xxxxxxxxxxxxxxxxxxxxxxxxxx
2020-04-30T09:06:10.445Z	INFO	Public server started on [::]:28967
2020-04-30T09:06:10.445Z	INFO	Private server started on 127.0.0.1:7778
2020-04-30T09:06:10.706Z	INFO	version	running on version v1.1.1
2020-04-30T09:06:23.549Z	INFO	piecestore	download started	{"Piece ID": "F6JYAFZAB456KQxxxxxxxxxx", "Satellite ID": "1wFTAgs9DP5RSnCqKV1eLfxxxxxxxxxxx", "Action": "GET"}

I have the automatic updates configured, according to the documentation:

https://documentation.storj.io/setup/cli/software-updates#automatic-updates

the watchtower container seems to be running correctly

On the other hand, I have tried to update manually as indicated in the documentation:

https://documentation.storj.io/setup/cli/software-updates#manual-updates

but the storagenode version is not updated.

Thanks in advance.

**Comment by ifraixedes** [comment] 2020-04-30 13:42
@angelsantillana94 as commented, the docker image will be updated after we rolled out the new version (v1.3.3) to all the Windows storage nodes.

There is a bug in the storage node UI about that notification, it shouldn't warn in this case.

**Comment by MaxMaximus** [comment] 2020-05-29 18:50
> 
> 
> @sixcorners @MaxMaximus I found out that the bug with the dashboard is fixed. The `v1.1.1` contains the bug but a later version shouldn't.
> 
> I'm closing the issue.
> Please wait until your nodes get updated to `v1.3.3` and if the issue persists then we'll reopen it.

Hello. Looks like you "overfix" this issue in  ver. 1.3.3. Now there are no any update notification in the node dashboard even after new version is available and already "rolled out" to a particular node.  I run 3 nodes still on v 1.3.3. and got no any notification after 1.4.2 and 1.5.2 releases in the DashBoard. (Although i have got message about outdated version via operator email from Storj server)

**Comment by ifraixedes** [comment] 2020-06-01 11:23
@MaxMaximus can you open a new issue just copying that text and linking to this one.
I see that's related but it's a different bug. I would do it myself but I would prefer that you do to keep who exactly has found it.

Once you open it, I will report it to our team who is in charge of these matters.

Thank you very much for reporting it.

**Comment by MaxMaximus** [comment] 2020-06-07 19:39
Ok, Done
