### ISSUE TITLE
My node is always restarting

### ISSUE THREAD

**Issue by monitorlivre** [storj/storj#1869] opened 2019-04-30 17:24 UTC
Hi
My node is always restarting:
"docker exec -it storagenode /app/dashboard.sh
Error response from daemon: Container 78ee9ec40eb3cf0dfb02557f655b590b89e62fb15abfbcb00a4804207d931934 is restarting, wait until the container is running"

The problem began when I updated the node.

2019-04-25T21:58:49.722Z INFO running on version v0.10.1
2019-04-25T21:58:49.743Z INFO db.migration Latest Version {"version": 5}
Fatal error: Error creating tables for master database on storagenode: migrate: creating version table failed: migrate: file is not a database
storj.io/storj/internal/migrate.(*Migration).Run:106
storj.io/storj/storagenode/storagenodedb.(*InfoDB).CreateTables:65
storj.io/storj/storagenode/storagenodedb.(*DB).CreateTables:120
main.cmdRun:158
storj.io/storj/pkg/process.cleanup.func1.2:252
storj.io/storj/pkg/process.cleanup.func1:266
github.com/spf13/cobra.(*Command).execute:762
github.com/spf13/cobra.(*Command).ExecuteC:852
github.com/spf13/cobra.(*Command).Execute:800
storj.io/storj/pkg/process.Exec:56
main.main:323
runtime.main:200 
![Captura de ecrã 2019-04-25, às 15 01 52](https://user-images.githubusercontent.com/43866173/56980626-be9f4c80-6b74-11e9-86a4-6ba9bad27228.jpg)
![Captura de ecrã 2019-04-25, às 15 03 27](https://user-images.githubusercontent.com/43866173/56980635-c3640080-6b74-11e9-9c0f-76bcdfd8cff2.jpg)

**Comment by aligeti** [comment] 2019-05-01 17:50
@monitorlivre what is the environment you running storgaenode on? can you send me some initial setup info?

**Comment by monitorlivre** [comment] 2019-05-01 19:58
Hi. After run yours sugestions, the problem is the same: 
![Captura de ecrã 2019-05-01, às 20 58 22](https://user-images.githubusercontent.com/43866173/57039192-e44f5300-6c53-11e9-933b-bd4dbb28c053.jpg)
Thanks

**Comment by monitorlivre** [comment] 2019-05-01 20:24
HiStoragenode is not running. I don't know what information to send to you. I folowed the guide and all was working fine, until follow the recommendation to run the line command for updates: docker run -d --restart=always --name watchtower -v /var/run/docker.sock:/var/run/docker.sock storjlabs/watchtowerI have shared in Storj Community chat all I have:----2019-04-25T21:58:48.940Z INFO Configuration loaded from: /app/config/config.yaml
2019-04-25T21:58:48.964Z INFO Operator email: monitorlivre@yahoo.com.com
2019-04-25T21:58:48.968Z INFO Operator wallet: 0x030B310e9A534798383F4aC02baCAf618CF850fC
2019-04-25T21:58:49.722Z INFO running on version v0.10.1
2019-04-25T21:58:49.743Z INFO db.migration Latest Version {"version": 5}
Fatal error: Error creating tables for master database on storagenode: migrate: creating version table failed: migrate: file is not a database
 storj.io/storj/internal/migrate.(*Migration).Run:106
 storj.io/storj/storagenode/storagenodedb.(*InfoDB).CreateTables:65
 storj.io/storj/storagenode/storagenodedb.(*DB).CreateTables:120
 main.cmdRun:158
 storj.io/storj/pkg/process.cleanup.func1.2:252
 storj.io/storj/pkg/process.cleanup.func1:266
 github.com/spf13/cobra.(*Command).execute:762
 github.com/spf13/cobra.(*Command).ExecuteC:852
 github.com/spf13/cobra.(*Command).Execute:800
 storj.io/storj/pkg/process.Exec:56
 main.main:323
 runtime.main:200 
____



    Em quarta-feira, 1 de maio de 2019, 18:50:50 WEST, aligeti<notifications@github.com> escreveu:  
 
 
@monitorlivre what is the environment you running storgaenode on? can you send me some initial setup info?

**Comment by Affinator** [comment] 2019-05-02 17:33
Similar problem on my side, but the error is slightly different:
2019-05-02T17:31:56.404145121Z Fatal error: Error creating tables for master database on storagenode: group:
2019-05-02T17:31:56.404339755Z --- migrate: creating version table failed: migrate: database is locked
2019-05-02T17:31:56.404406108Z  storj.io/storj/internal/migrate.(*Migration).Run:106
2019-05-02T17:31:56.404469598Z  storj.io/storj/storagenode/storagenodedb.(*DB).CreateTables:119
2019-05-02T17:31:56.404531733Z  main.cmdRun:158
2019-05-02T17:31:56.404593034Z  storj.io/storj/pkg/process.cleanup.func1.2:252
2019-05-02T17:31:56.404654648Z  storj.io/storj/pkg/process.cleanup.func1:266
2019-05-02T17:31:56.404716158Z  github.com/spf13/cobra.(*Command).execute:762
2019-05-02T17:31:56.404776835Z  github.com/spf13/cobra.(*Command).ExecuteC:852
2019-05-02T17:31:56.404838605Z  github.com/spf13/cobra.(*Command).Execute:800
2019-05-02T17:31:56.404899438Z  storj.io/storj/pkg/process.Exec:56
2019-05-02T17:31:56.404960427Z  main.main:323
2019-05-02T17:31:56.405021833Z  runtime.main:200
2019-05-02T17:31:56.405082406Z --- migrate: creating version table failed: migrate: database is locked
2019-05-02T17:31:56.405144072Z  storj.io/storj/internal/migrate.(*Migration).Run:106
2019-05-02T17:31:56.405205790Z  storj.io/storj/storagenode/storagenodedb.(*InfoDB).CreateTables:65
2019-05-02T17:31:56.405268238Z  storj.io/storj/storagenode/storagenodedb.(*DB).CreateTables:120
2019-05-02T17:31:56.405442351Z  main.cmdRun:158
2019-05-02T17:31:56.405517819Z  storj.io/storj/pkg/process.cleanup.func1.2:252
2019-05-02T17:31:56.405580267Z  storj.io/storj/pkg/process.cleanup.func1:266
2019-05-02T17:31:56.405641621Z  github.com/spf13/cobra.(*Command).execute:762
2019-05-02T17:31:56.405702141Z  github.com/spf13/cobra.(*Command).ExecuteC:852
2019-05-02T17:31:56.405763443Z  github.com/spf13/cobra.(*Command).Execute:800
2019-05-02T17:31:56.405824484Z  storj.io/storj/pkg/process.Exec:56
2019-05-02T17:31:56.405885890Z  main.main:323
2019-05-02T17:31:56.405945889Z  runtime.main:200

Running on a raspberry pi 3b with Linux raspberrypi 4.19.36-v7+ #1212 SMP Tue Apr 23 12:28:46 BST 2019 armv7l GNU/Linux.

**Comment by ReneSmeekes** [comment] 2019-05-03 11:24
@Affinator this is not a similar issue. Your issue has to do with file access rights, likely because you are using a network share as your storage location. This is not supported, use iSCSI instead. It's not related to the "file is not a database" issue, which is likely caused by corruption.

**Comment by jacek-kubek** [comment] 2019-05-13 19:16
The same here (like @monitorlivre has reported).
Even after cleaning with `docker system prune`.
The node has run one week (about 20g of data in storage/). Now it is restarting every one minute:
```
2019-05-13T18:57:15.736087430Z 2019-05-13T18:57:15.735Z	INFO	Configuration loaded from: /app/config/config.yaml
2019-05-13T18:57:15.749173268Z 2019-05-13T18:57:15.749Z	INFO	Operator email: XXXXXXXXXXXXXXXXXXXXXXX
2019-05-13T18:57:15.749231835Z 2019-05-13T18:57:15.749Z	INFO	Operator wallet: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2019-05-13T18:57:16.701848008Z 2019-05-13T18:57:16.701Z	INFO	running on version v0.11.1
2019-05-13T18:57:16.706635147Z 2019-05-13T18:57:16.706Z	INFO	db.migration	Latest Version	{"version": 0}
2019-05-13T18:57:16.706742351Z 2019-05-13T18:57:16.706Z	INFO	db.migration.1	Network Wipe #2
2019-05-13T18:57:16.778580861Z Fatal error: Error creating tables for master database on storagenode: migrate: database disk image is malformed
2019-05-13T18:57:16.778683244Z 	storj.io/storj/internal/migrate.(*Migration).Run:135
2019-05-13T18:57:16.778703340Z 	storj.io/storj/storagenode/storagenodedb.(*InfoDB).CreateTables:65
2019-05-13T18:57:16.778718878Z 	storj.io/storj/storagenode/storagenodedb.(*DB).CreateTables:102
2019-05-13T18:57:16.778733727Z 	main.cmdRun:159
2019-05-13T18:57:16.778748490Z 	storj.io/storj/pkg/process.cleanup.func1.2:259
2019-05-13T18:57:16.778762890Z 	storj.io/storj/pkg/process.cleanup.func1:273
2019-05-13T18:57:16.778776794Z 	github.com/spf13/cobra.(*Command).execute:762
2019-05-13T18:57:16.778790657Z 	github.com/spf13/cobra.(*Command).ExecuteC:852
2019-05-13T18:57:16.778804352Z 	github.com/spf13/cobra.(*Command).Execute:800
2019-05-13T18:57:16.778817927Z 	storj.io/storj/pkg/process.Exec:56
2019-05-13T18:57:16.778831985Z 	main.main:288
2019-05-13T18:57:16.778845897Z 	runtime.main:200
```

**Comment by aligeti** [comment] 2019-05-13 19:21
While I find the solution...my notes has this solution to try for the similar problem:

Fatal errors:
- File is not a database. (happened after node update through watchtower) Asked user to file Github issue. Not sure if they ended up doing that. Can't find it right now.
- Database disk image is malformed. Try this solution: https://www.sysinfotools.com/blog/fix-error-sqlite-database-disk-image-malformed/

**Comment by jacek-kubek** [comment] 2019-05-13 20:51
@aligeti thank you help. I have followed your tip (https://www.sysinfotools.com/blog/fix-error-sqlite-database-disk-image-malformed/) and repaired `info.db`. My node is working again now. I can only guess, this file was corrupted during upgrade made by `watchtower`.

**Comment by aligeti** [comment] 2019-05-14 14:41
@jacek-kubek for the benefit of community can you please write down the steps you took to fix the problem. 
Environment:

Steps:

Appreciate the help. I am glad it worked.

**Comment by jacek-kubek** [comment] 2019-05-14 19:28
@aligeti 
### Environment:
1. Headless `storagenode` `<server>`
    ````
    <server>:~$ hostnamectl 
    [...]
    Operating System: Debian GNU/Linux 9 (stretch)
    Kernel: Linux 4.9.0-9-amd64
    Architecture: x86-64
    <server>:~$ docker images
    REPOSITORY              TAG                 [...]
    storjlabs/storagenode   alpha               [...]
    storjlabs/watchtower    latest              [...]
    [...]
    <server>:~$ ls <storage-dir>/
    config.yaml  kademlia  revocations.db  storage
    <server>:~$ ls <storage-dir>/storage/
    blob  info.db  piecestore.db  tmp  trash
    ````
2. X Window capable `<laptop>`
    ````
    <laptop>:~$ hostnamectl 
    [...]
    Operating System: LMDE 3 (cindy)
    Kernel: Linux 4.9.0-9-amd64
    Architecture: x86-64
    ````
### Steps:
1. `<server>:~$ docker stop storagenode`
2. `<server>:~$ scp <storage-dir>/storage/info.db <user>@<laptop>:/home/<user>/`
3. `<laptop>:~$ sudo apt install sqlitebrowser`
4. `<laptop>:~$ sqlitebrowser`
   1. `File` `Open Database...` `/home/<user>/info.db`
   2. go to `Execute SQL` tab
   3. enter `PRAGMA integrity_check;` in SQL box
   4. execute SQL (`F5`)
   5. observe result box - if `ok`, you do not need to fix `info.db` (go strait to 6.)
   6. `File` `Export` `Database to SQL file...`
   7. `File` `Import` `Database from SQL file...` creating `info.db.new`
   8. `File` `Exit`
5. `<server>:~$ scp <user>@<laptop>:/home/<user>/info.db.new <storage-dir>/storage/info.db`
6. `<server>:~$ docker start storagenode`
7. `<server>:~$ docker ps`
   - check `STATUS` of  `storagenode`, should be `Up ...`

**Comment by AlexeyALeonov** [comment] 2019-07-12 11:42
it doesn't help for "file is not a database" unfortunately

**Comment by DMcP89** [comment] 2019-07-24 04:34
I am experiencing this issue as well on 0.15.3

Here is what i see in my logs

`2019-07-24T02:55:07.097Z        INFO    Configuration loaded from: /app/config/config.yaml
2019-07-24T02:55:07.100Z        INFO    Operator email: dmcp89@gmail.com
2019-07-24T02:55:07.100Z        INFO    Operator wallet: 0x2f40208b2edc15347d9ec9079fbe41a67ac53a74
2019-07-24T02:55:14.740Z        INFO    running on version v0.15.3
2019-07-24T02:55:14.758Z        INFO    db.migration    Latest Version  {"version": 13}
2019-07-24T02:55:14.760Z        INFO    vouchers        Checking vouchers
2019-07-24T02:55:14.763Z        INFO    Node 129i4wWwwSgqtGNcY6KgLEwpFNo5zq4UGMYkDqMbzHU1QX92pkm started
2019-07-24T02:55:14.763Z        INFO    Public server started on [::]:28967
2019-07-24T02:55:14.763Z        INFO    Private server started on 127.0.0.1:7778
2019-07-24T02:55:14.793Z        INFO    running on version v0.15.3
ERROR: 2019/07/24 02:55:14 pickfirstBalancer: failed to NewSubConn: rpc error: code = Canceled desc = grpc: the client connection is closing
ERROR: 2019/07/24 02:55:14 pickfirstBalancer: failed to NewSubConn: rpc error: code = Canceled desc = grpc: the client connection is closing
ERROR: 2019/07/24 02:55:14 pickfirstBalancer: failed to NewSubConn: rpc error: code = Canceled desc = grpc: the client connection is closing
2019-07-24T02:55:14.945Z        INFO    piecestore:orderssender.12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S     sending {"count": 8}
2019-07-24T02:55:14.945Z        INFO    piecestore:orderssender.118UWpMCHzs6CvSgWd9BfFVjw5K9pZbJjkfZJexMtSkmKxvvAW      sending {"count": 2060}
2019-07-24T02:55:14.946Z        INFO    piecestore:orderssender.12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs     sending {"count": 6}
2019-07-24T02:55:14.945Z        INFO    piecestore:orderssender.121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6     sending {"count": 35}
2019-07-24T02:55:14.948Z        INFO    piecestore:orderssender.118UWpMCHzs6CvSgWd9BfFVjw5K9pZbJjkfZJexMtSkmKxvvAW      finished
2019-07-24T02:55:14.948Z        ERROR   piecestore:orderssender.118UWpMCHzs6CvSgWd9BfFVjw5K9pZbJjkfZJexMtSkmKxvvAW      failed to settle orders     {"error": "order: unable to find satellite on the network: context canceled", "errorVerbose": "order: unable to find satellite on the network: context canceled\n\tstorj.io/storj/storagenode/orders.(*Sender).settle:156\n\tstorj.io/storj/storagenode/orders.(*Sender).Settle:142\n\tstorj.io/storj/storagenode/orders.(*Sender).runOnce.func1:127\n\tgolang.org/x/sync/errgroup.(*Group).Go.func1:57"}
2019-07-24T02:55:14.949Z        INFO    piecestore:orderssender.12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S     finished
2019-07-24T02:55:14.949Z        ERROR   piecestore:orderssender.12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S     failed to settle orders     {"error": "order: unable to find satellite on the network: context canceled", "errorVerbose": "order: unable to find satellite on the network: context canceled\n\tstorj.io/storj/storagenode/orders.(*Sender).settle:156\n\tstorj.io/storj/storagenode/orders.(*Sender).Settle:142\n\tstorj.io/storj/storagenode/orders.(*Sender).runOnce.func1:127\n\tgolang.org/x/sync/errgroup.(*Group).Go.func1:57"}
ERROR: 2019/07/24 02:55:14 pickfirstBalancer: failed to NewSubConn: rpc error: code = Canceled desc = grpc: the client connection is closing
2019-07-24T02:55:14.951Z        INFO    piecestore:orderssender.121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6     finished
2019-07-24T02:55:14.951Z        ERROR   piecestore:orderssender.121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6     failed to settle orders     {"error": "order: unable to find satellite on the network: context canceled", "errorVerbose": "order: unable to find satellite on the network: context canceled\n\tstorj.io/storj/storagenode/orders.(*Sender).settle:156\n\tstorj.io/storj/storagenode/orders.(*Sender).Settle:142\n\tstorj.io/storj/storagenode/orders.(*Sender).runOnce.func1:127\n\tgolang.org/x/sync/errgroup.(*Group).Go.func1:57"}
2019-07-24T02:55:14.956Z        INFO    piecestore:orderssender.12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs     finished
2019-07-24T02:55:14.956Z        ERROR   piecestore:orderssender.12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs     failed to settle orders     {"error": "order: unable to find satellite on the network: context canceled", "errorVerbose": "order: unable to find satellite on the network: context canceled\n\tstorj.io/storj/storagenode/orders.(*Sender).settle:156\n\tstorj.io/storj/storagenode/orders.(*Sender).Settle:142\n\tstorj.io/storj/storagenode/orders.(*Sender).runOnce.func1:127\n\tgolang.org/x/sync/errgroup.(*Group).Go.func1:57"}
ERROR: 2019/07/24 02:55:14 pickfirstBalancer: failed to NewSubConn: rpc error: code = Canceled desc = grpc: the client connection is closing
2019-07-24T02:55:14.989Z        INFO    piecestore:monitor      Remaining Bandwidth     {"bytes": 271733286912}
2019-07-24T02:55:15.047Z        ERROR   collector       error during collecting pieces:         {"error": "infodb: context canceled", "errorVerbose": "infodb: context canceled\n\tstorj.io/storj/storagenode/storagenodedb.(*pieceinfo).GetExpired:186\n\tstorj.io/storj/storagenode/collector.(*Service).Collect:87\n\tstorj.io/storj/storagenode/collector.(*Service).Run.func1:53\n\tstorj.io/storj/internal/sync2.(*Cycle).Run:87\n\tstorj.io/storj/storagenode/collector.(*Service).Run:52\n\tstorj.io/storj/storagenode.(*Peer).Run.func4:345\n\tgolang.org/x/sync/errgroup.(*Group).Go.func1:57"}`

This gets repeated each time the node restarts. I have tried all the suggestions with no luck. I have watch tower setup for automatic updates so I should be on the latest release.

**Comment by AlexeyALeonov** [comment] 2019-07-24 08:26
@DMcP89 Please, replace the `info` level to `debug` in the `config.yaml`, save the file and restart the container: `docker restart -t 300 storagenode`
Then copy the output of this command: `docker logs storagenode 2>&1 | grep -B 3 -i fatal`

I think your issue is related to #2607

**Comment by ReneSmeekes** [comment] 2019-07-24 09:01
FYI that PR has been superceded by this more complete solution in the works https://github.com/storj/storj/pull/2617

**Comment by DMcP89** [comment] 2019-07-24 22:23
@AlexeyALeonov 

Appears to be an issue the the infodb?

> ERROR: 2019/07/24 22:18:45 pickfirstBalancer: failed to NewSubConn: rpc error: code = Canceled desc = grpc: the client connection is closing
2019-07-24T22:18:45.586Z        INFO    piecestore:monitor      Remaining Bandwidth     {"bytes": 271618660608}
ERROR: 2019/07/24 22:18:45 pickfirstBalancer: failed to NewSubConn: rpc error: code = Canceled desc = grpc: the client connection is closing
2019-07-24T22:18:46.523Z        DEBUG   Fatal error: infodb: UNIQUE constraint failed: bandwidth_usage_rollups.interval_start, bandwidth_usage_rollups.satellite_id, bandwidth_usage_rollups.action
--
2019-07-24T22:20:31.601Z        INFO    piecestore:orderssender.121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6     finished
2019-07-24T22:20:31.601Z        ERROR   piecestore:orderssender.121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6     failed to settle orders     {"error": "order: unable to find satellite on the network: context canceled", "errorVerbose": "order: unable to find satellite on the network: context canceled\n\tstorj.io/storj/storagenode/orders.(*Sender).settle:156\n\tstorj.io/storj/storagenode/orders.(*Sender).Settle:142\n\tstorj.io/storj/storagenode/orders.(*Sender).runOnce.func1:127\n\tgolang.org/x/sync/errgroup.(*Group).Go.func1:57"}
ERROR: 2019/07/24 22:20:31 pickfirstBalancer: failed to NewSubConn: rpc error: code = Canceled desc = grpc: the client connection is closing
2019-07-24T22:20:32.502Z        DEBUG   Fatal error: infodb: UNIQUE constraint failed: bandwidth_usage_rollups.interval_start, bandwidth_usage_rollups.satellite_id, bandwidth_usage_rollups.action
--
ERROR: 2019/07/24 22:21:33 pickfirstBalancer: failed to NewSubConn: rpc error: code = Canceled desc = grpc: the client connection is closing
2019-07-24T22:21:33.480Z        INFO    piecestore:monitor      Remaining Bandwidth     {"bytes": 271618660608}
ERROR: 2019/07/24 22:21:33 pickfirstBalancer: failed to NewSubConn: rpc error: code = Canceled desc = grpc: the client connection is closing
2019-07-24T22:21:34.418Z        DEBUG   Fatal error: infodb: UNIQUE constraint failed: bandwidth_usage_rollups.interval_start, bandwidth_usage_rollups.satellite_id, bandwidth_usage_rollups.action

**Comment by AlexeyALeonov** [comment] 2019-07-24 23:47
@DMcP89 
No. Bug in the code. Take a look on https://github.com/storj/storj/pull/2617 above

**Comment by DMcP89** [comment] 2019-07-24 23:57
@AlexeyALeonov  I see. So in terms of a work around I would have to manually go into the DB and remove the duplicate entry? or is there a way to refresh the info.db?

**Comment by AlexeyALeonov** [comment] 2019-07-25 00:02
Workaround at the moment is only to remove duplicated entries from the DB. The node should be stopped during the procedure.

**Comment by DMcP89** [comment] 2019-07-26 02:22
@AlexeyALeonov  any ideas on how to identify the duplicates? I tried this sql but it returns 0 rows.

`
SELECT bandwidth_usage_rollups.interval_start, bandwidth_usage_rollups.satellite_id, bandwidth_usage_rollups.action, COUNT(*)
FROM bandwidth_usage_rollups
GROUP BY bandwidth_usage_rollups.interval_start, bandwidth_usage_rollups.satellite_id, bandwidth_usage_rollups.action
HAVING COUNT(*) > 1
`

Any type of logging I can turn on to see what its trying to insert?

**Comment by AlexeyALeonov** [comment] 2019-07-26 19:24
@DMcP89 I don't know, where you took that script, but it should be a different: https://forum.storj.io/t/debug-fatal-error-infodb-unique-constraint-failed-bandwidth-usage-rollups-interval-start/698/4?u=alexey

**Comment by DMcP89** [comment] 2019-07-28 16:57
@AlexeyALeonov  that did the trick, thanks for the help!

**Closed** 2019-07-29 09:37 UTC
