### ISSUE TITLE
Remove the partner ID columns from all db tables (after migration occurs)

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4366] opened 2022-01-13 00:02 UTC
this column is going to stay in the DB if we don't remove it. currently, it is not being used anywhere.

**Comment by mobyvb** [comment] 2023-04-05 13:54
@cam-a do you know if we did this already?

**Comment by mobyvb** [comment] 2023-09-06 20:41
closing
duplicate of https://github.com/storj/storj/issues/5432

**Closed by mobyvb** 2023-09-06 20:41 UTC
Labels: Priority: Low
