### ISSUE TITLE
storj-sim network run error

### ISSUE THREAD

**Issue by chrismeyersfsu** [storj/storj#4017] opened 2021-01-03 00:44 UTC
satellite servers fails with the bellow error when trying to start the storj sim.

`satellite/0                               19:39:08.969 | DEBUG  Unrecoverable error     {"error": "Auth token secret required", "errorVerbose": "Auth token secret required\n\tstorj.io/storj/satellite.NewAPI:568\n\tmain.cmdAPIRun:73\n\tstorj.io/private/process.cleanup.func1.4:349\n\tstorj.io/private/process.cleanup.func1:367\n\tgithub.com/spf13/cobra.(*Command).execute:840\n\tgithub.com/spf13/cobra.(*Command).ExecuteC:945\n\tgithub.com/spf13/cobra.(*Command).Execute:885\n\tstorj.io/private/process.ExecWithCustomConfig:88\n\tstorj.io/private/process.ExecCustomDebug:70\n\tmain.main:719\n\truntime.main:203"}`

I tried defining `console.auth-token-secret` in `~/.local/share/storj/local-network/satellite/0/config.yaml` but then got node signing errors. Not sure what to do.

**Comment by egonelbre** [comment] 2021-01-05 11:07
Ah, I think I know what's going on.

Our current config handling is somewhat unintuitive. So if you use a release branch (properly tagged) or downloaded then it will run in "production" mode... however, storj-sim should always run in dev mode.

I'll make a fix to ensure all the binaries are started in "dev" mode.

**Comment by egonelbre** [comment] 2021-01-05 12:49
Should be fixed by https://github.com/storj/storj/commit/9cb4466eb0a24bb9bf48c59fc9e7eed73a81b632.

Please, reopen if the issue is still there.

**Closed by egonelbre** 2021-01-05 12:49 UTC

**Comment by chrismeyersfsu** [comment] 2021-01-05 13:47
Thanks for looking into this @egonelbre that was most certainly it. The simulator worked out of the `main` branch.

Another thought, as a new user, I had no indicator of whether the simulator successfully started or not. Some ideas:
* Have a flag to fail hard when any piece fails
* Fail if any startup or bootstrap process fails
* print a known, documented message after the init processes finishes indicating success/failure
* build out a dashboard that shows the status of the simulator

**Comment by egonelbre** [comment] 2021-01-05 14:06
> Fail if any startup or bootstrap process fails

Sometimes we intentionally kill storagenode to see how the system behaves under stresses.

> print a known, documented message after the init processes finishes indicating success/failure

It depends on what you mean by "finishes". Since the whole system starts up concurrently there can be multiple ways it may have finished. For example whether the binaries have started or whether it's capable of responding to requests.

Inside scripts you can use `storj-sim tool wait-for` to wait for a particular port to become alive.

Alternatively, if you are running tests, then maybe using `storj-sim network test` might be more helpful.

> build out a dashboard that shows the status of the simulator

Yeah, I've been planning to do that, but it hasn't been high on the priority list with all the other things ongoing.

> Have a flag to fail hard when any piece fails

Yeah, that does sound like a good easy feature to include. e.g. `storj-sim network run --fail-fast` or something.

**Comment by egonelbre** [comment] 2021-01-06 14:46
I added `-failfast` in https://github.com/storj/storj/commit/b33d7a318ec5ba94b231eff8d0460f4821f008c0
