### ISSUE TITLE
Add Object lock  to Versioning beta in UI 

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#7063] opened 2024-07-24 04:13 UTC
- Add object lock information to the project settings related to versioning beta
- Update versioning beta to include information about object lock

**Comment by ferristocrat** [comment] 2024-07-24 04:14
@boshevski created this placeholder

**Comment by NiaStorj** [comment] 2024-07-26 21:27
@boshevski what eta on the design?

**Comment by boshevski** [comment] 2024-07-29 15:25
Looks like this is a copy of another ticket where the designs for review are attached: https://github.com/storj/storj/issues/7057

**Comment by mobyvb** [comment] 2024-07-30 14:03
we need to talk with @jewharton and @wilfred-asomanii to make sure we combine object lock with the versioning beta in an appropriate way

**Comment by wilfred-asomanii** [comment] 2024-08-05 13:29
Closing as duplicate of #7057 which has more information

**Closed by wilfred-asomanii** 2024-08-05 13:29 UTC
Labels: Satellite UI, needs discussion
