### ISSUE TITLE
Satellite UI - update folder creation in the file browser

### ISSUE THREAD

**Issue by lizzythomson** [storj/storj#5102] opened 2022-08-23 16:02 UTC
Update folder upload in the file browser to match the figma designs below

Figma: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=17178%3A168014

**Comment by mobyvb** [comment] 2022-09-07 14:04
duplicate of https://github.com/storj/storj/issues/4947

**Closed by mobyvb** 2022-09-07 14:04 UTC
