### ISSUE TITLE
Error response from deamon and can not up date

### ISSUE THREAD

**Issue by Byrd1083** [storj/storj#3586] opened 2019-11-15 16:20 UTC
Been stable for a week. Rebooted for windows updated. Started back up and now the deamon will not run correctly and throws me errors. I tried removing the container and the redoing it. Still same results. I ran log and see it keeps saying I'm not up to date. I have had watch tower going so not sure why it did not auto update. I guess I'm offline till I get some help, any ideas?

![image](https://user-images.githubusercontent.com/42227809/68957857-c1176b80-077f-11ea-8027-b6695aaea746.png)

![image](https://user-images.githubusercontent.com/42227809/68958348-c9bc7180-0780-11ea-9ae2-22fd76cdb165.png)

**Comment by kaloyan-raev** [comment] 2019-11-18 13:18
@Byrd1083 thank you for reporting this issue!

If your storage node is still not up-to-date, we would be curious to see the logs of the watchtower. Please execute the following steps:

1. Remove the existing watchtower container:
```sh
docker run -d --restart=always --name watchtower -v /var/run/docker.sock:/var/run/docker.sock storjlabs/watchtower storagenode watchtower --stop-timeout 300s --interval 21600
```
2. Run a new watchtower container in debug mode:
```sh
docker run -d --restart=always --name watchtower -v /var/run/docker.sock:/var/run/docker.sock storjlabs/watchtower storagenode watchtower --stop-timeout 300s --interval 21600 -- debug
```
3. Print the logs after 6 hours:
```sh
docker logs watchtower
```

Alternatively, you can follow the steps for manually updating the storagenode container: https://documentation.storj.io/setup/cli/software-updates#manual-updates

Also, we now have a Docker-less installation for Windows you can switch to if you don't want to deal with Docker: https://documentation.storj.io/setup/gui-windows/storage-node

**Comment by stefanbenten** [comment] 2019-12-12 10:39
@Byrd1083 Did you had any change to execute the steps that we outlined in the comment from @kaloyan-raev ?
If the issue is solved, please report back so that we can close the issue.

**Closed** 2020-12-04 18:54 UTC
Labels: Waiting for Feedback
