### ISSUE TITLE
Storage node isnt show stat at localhost:14002

### ISSUE THREAD

**Issue by Quake4** [storj/storj#3683] opened 2019-12-03 09:49 UTC
![image](https://user-images.githubusercontent.com/29517243/70039622-4b0e6380-15cb-11ea-88bd-5fe71ae236cd.png)

**Comment by NikolaiYurchenko** [comment] 2019-12-03 11:17
Hi @Quake4, Can you provide additional information about: OS, environment and browser you are using? Also how exactly you are setuping storage node dashboard and which version you are using.

**Comment by Quake4** [comment] 2019-12-03 11:49
Win7, Yandex Browser 19.12.0.358. 0.26.2
manual run `storagenode_windows_amd64.exe`

**Comment by Quake4** [comment] 2019-12-03 11:51
do you think the wrong mime type is affected by the environment?

**Comment by ifraixedes** [comment] 2019-12-03 13:47
> Do you think the wrong mime type is affected by the environment?
I thought the MIME type code for all js files in SNserver was misplaced (content-type: text/javascript).

That makes sense, however, other users aren't experimenting that as far as we know.

I'm in doubt if you can see anything or not in the browser a part of having those errors in the web console, do you?

On the other hand, can you try to load the dashboard with Chrome or Firefox? we know that it doesn't work on Internet Explorer, so perhaps Yandex Browser either.

**Comment by Quake4** [comment] 2019-12-03 15:00
The browser have a blank page. Do not have chrome, fox. I try edge later.

**Comment by Quake4** [comment] 2019-12-03 19:00
edge have same mismatch proper mime type for JS files
![image](https://user-images.githubusercontent.com/29517243/70080827-576cdd80-1618-11ea-88c9-dbcb1c7e8147.png)

**Comment by ifraixedes** [comment] 2019-12-04 09:53
@Quake4 thanks for checking with Edge. We know that Edge didn't work and we have a ticket for resolving it. The problem with those browsers may be due to what you highlighted while others ignore the issue and just work.

I'm going to open a new ticket for the Yandex browser problem and report this information into the existing Internet Explorer ticket.

**Comment by Quake4** [comment] 2019-12-04 13:06
Its default browser configurations. But I don't see the difficulty to change JS mime type in NSserver to proper value `text/javascript` from`text/plain`.

**Comment by Kaallee** [comment] 2019-12-14 19:08
I'm pushing this issue. I'm facing the same problem on MS Windows Server  2019 Datacenter.

**Comment by Quake4** [comment] 2019-12-17 04:43
27.1 still exists

**Comment by Quake4** [comment] 2019-12-19 11:24
28,2 still exists

**Comment by sixcorners** [comment] 2020-01-27 14:40
I get this issue in chrome.

**Comment by ifraixedes** [comment] 2020-01-27 15:55
It's still in our backlog, we'll try to prioritize it.

Thanks for your patience.

**Comment by ifraixedes** [comment] 2020-01-29 16:41
I've checked with curl and I see that the server sends the correct `Content-Type` header value for `vendor.js`

```
-> curl 'http://localhost:14002/static/dist/js/vendors.js' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36' -H 'Accept: */*' -H 'Referer: http://192.168.1.20:14002/' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.9' --compressed --insecure -D - -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: public, max-age=31536000
Content-Length: 597922
Content-Type: application/javascript
Last-Modified: Wed, 22 Jan 2020 12:12:31 GMT
X-Content-Type-Options: nosniff
Date: Wed, 29 Jan 2020 16:38:13 GMT

100  583k  100  583k    0     0  3185k      0 --:--:-- --:--:-- --:--:-- 3190k
```

and `app.js`

```
curl 'http://localhost:14002/static/dist/js/app.js' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36' -H 'Accept: */*' -H 'Referer: http://192.168.1.20:14002/' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.9' --compressed --insecure -D - -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: public, max-age=31536000
Content-Length: 96834
Content-Type: application/javascript
Last-Modified: Wed, 22 Jan 2020 12:12:31 GMT
X-Content-Type-Options: nosniff
Date: Wed, 29 Jan 2020 16:38:41 GMT

100 96834  100 96834    0     0  2248k      0 --:--:-- --:--:-- --:--:-- 2251k
```

even if I don't send any header in the `curl` requests, I get the same result.

Hence, I don't understand what's going with those browsers.

**Comment by Quake4** [comment] 2020-01-29 19:58
![image](https://user-images.githubusercontent.com/29517243/73392446-e6316a00-42ea-11ea-8e21-d9db8f2938d7.png)

**Comment by Quake4** [comment] 2020-01-29 19:59
![image](https://user-images.githubusercontent.com/29517243/73392475-f3e6ef80-42ea-11ea-8321-0e52566ba5af.png)

**Comment by Quake4** [comment] 2020-01-29 19:59
0.30.5

**Comment by Quake4** [comment] 2020-01-29 20:03
try locally

**Comment by ifraixedes** [comment] 2020-01-30 09:16
Can you try with `curl`, please?

**Comment by Quake4** [comment] 2020-01-30 09:55
![image](https://user-images.githubusercontent.com/29517243/73438879-cd16d080-435f-11ea-98de-b61c20c1f63f.png)

**Comment by Quake4** [comment] 2020-01-30 10:07
For me, devconsole from the browser is more reliable.

**Comment by Quake4** [comment] 2020-01-30 10:12
0.31.9 still exists

**Comment by ifraixedes** [comment] 2020-01-30 10:59
I did the web console too and it's fine for Chromium and Firefox.
The `Content-Type` header is sent by the HTTP server, it shouldn't matter what does the request if it does with the same URL, parameters, and headers.

As I said before, I did `curl` without any header and the result was the same, but here it goes with `v0.31.9`

```
-> curl 'http://localhost:14002/static/dist/js/app.js' -D - -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: public, max-age=31536000
Content-Length: 96834
Content-Type: application/javascript
Last-Modified: Thu, 30 Jan 2020 01:44:51 GMT
X-Content-Type-Options: nosniff
Date: Thu, 30 Jan 2020 10:57:19 GMT

100 96834  100 96834    0     0  3006k      0 --:--:-- --:--:-- --:--:-- 3152k
```

So the problem that we are having is that we are not able to reproduce what you're getting, so we are stuck on it until we could.

**Comment by Quake4** [comment] 2020-01-30 11:34
just try on windows storage node

**Comment by ifraixedes** [comment] 2020-01-30 15:40
Ok, that's good to know.
I'll ask somebody to try it because I'm not able to do so.

**Comment by tempestb** [comment] 2020-01-30 16:29
![image](https://user-images.githubusercontent.com/21684587/73469034-ba969a00-4353-11ea-81f3-ef02e38af285.png)

It works fine on my Windows node.  Here's my Curl results.

**Comment by Quake4** [comment] 2020-01-31 05:11
it's great that it works for you, but it doesn't work for us.

**Comment by Quake4** [comment] 2020-01-31 05:44
0.31.12 still exists

**Comment by ifraixedes** [comment] 2020-01-31 16:59
@Quake4 @tempestb posted his result because it's what I could reach to give a try in a windows installation. His intention was to show that for him works rather than we are trying to reproduce your issue for being able to troubleshoot.

**Comment by Quake4** [comment] 2020-01-31 20:16
I can run the debug version if you give me.

**Comment by ifraixedes** [comment] 2020-02-03 12:47
I'm not aware that we have any debug version. You can run the node with the DEBUG log level, but I don't think that it will help to see what's going on.

**Comment by egonelbre** [comment] 2020-02-03 13:38
@Quake4 I made a change in https://review.dev.storj.io/c/storj/storj/+/813 to hopefully fix the issue. It'll take some time to get deployed.

The issue is that http.FileServer we are using to serve the static files is using `Content-Type`-s specified the operating system. So for example your OS could have ".js" set as "application/javascript". It makes sense to have only one place to configure them rather than multiple on a server.

The fix overrides any common content-type and instead uses one from the predefined list.

**Comment by Quake4** [comment] 2020-02-04 08:46
@egonelbre Where is in Win set of mimetypes?

**Comment by egonelbre** [comment] 2020-02-04 10:14
It's keeping it in registry `HKEY_CLASSES_ROOT\.js` and see the `Content Type` key.

**Comment by Quake4** [comment] 2020-02-04 10:21
![image](https://user-images.githubusercontent.com/29517243/73736011-2c565580-4751-11ea-967e-d16c4fa6581f.png)
yes - text/plain ;(

**Comment by Quake4** [comment] 2020-02-04 10:23
on other machine - fine
![image](https://user-images.githubusercontent.com/29517243/73736269-8b1bcf00-4751-11ea-86b1-766199e02b6e.png)

**Comment by Quake4** [comment] 2020-02-04 10:23
thank you, for fix

**Closed** 2020-02-19 08:12 UTC
Labels: Bug, Tracked in Jira
