### ISSUE TITLE
After Update to 1.78.3: file or directory not found: open \\identity.cert: The system cannot find the file specified

### ISSUE THREAD

**Issue by stricq** [storj/storj#5899] opened 2023-05-20 18:43 UTC
My node has been exiting for several weeks now.  I routinely run this command to check the exit status:

"C:\Program Files\Storj\Storage Node\storagenode.exe" exit-status --identity-dir "C:\Users\Me\AppData\Roaming\Storj\Identity\storagenode" --log.output stderr

Before updating to 1.78.3, this command would show the current exit status as described in the documentation.  After updating to 1.78.3 I now get this error:

2023-05-20T12:23:16.993-0600    INFO    Anonymized tracing enabled      {"Process": "storagenode"}
2023-05-20T12:23:17.000-0600    FATAL   Failed to load identity.        {"Process": "storagenode", "error": "file or directory not found: open \\identity.cert: The system cannot find the file specified.", "errorVerbose": "file or directory not found: open \\identity.cert: The system cannot find the file specified.\n\tstorj.io/common/identity.Config.Load:326\n\tmain.cmdGracefulExitStatus:186\n\tmain.newGracefulExitStatusCmd.func1:59\n\tstorj.io/private/process.cleanup.func1.4:399\n\tstorj.io/private/process.cleanup.func1:417\n\tgithub.com/spf13/cobra.(*Command).execute:852\n\tgithub.com/spf13/cobra.(*Command).ExecuteC:960\n\tgithub.com/spf13/cobra.(*Command).Execute:897\n\tstorj.io/private/process.ExecWithCustomOptions:113\n\tmain.main:29\n\truntime.main:250"}

I have verified that the identity.cert file exists in the given directory.

This is running under Windows 10.

The node itself is running fine and I can still access the website to see the current status.  It's just the command line exit-status that is failing.

**Comment by profclems** [comment] 2023-05-25 02:00
Duplicate of #5807 which is fixed by https://github.com/storj/storj/commit/bf8072d3f3706bdd020db89149a0ed51632f0ea4. 

The fix should be in the next release.

**Closed by profclems** 2023-05-25 02:00 UTC
Labels: Bug

**Comment by profclems** [comment] 2023-05-25 02:06
The workaround you can use before the fix is deployed is to explicitly specify the `--identity.cert-path` and `--identity.key-path`

```sh
storagenode.exe exit-status --identity-dir "C:\Users\Me\AppData\Roaming\Storj\Identity\storagenode" --log.output stderr --identity.cert-path "C:\Users\Me\AppData\Roaming\Storj\Identity\storagenode\identity.cert" --identity.key-path "C:\Users\Me\AppData\Roaming\Storj\Identity\storagenode\identity.key"
```

**Comment by AlexeyALeonov** [comment] 2023-05-25 04:09
The other way is provide a path to the config file, i.e.
```
"C:\Program Files\Storj\Storage Node\storagenode.exe" exit-status --config-dir "C:\Program Files\Storj\Storage Node\\" --log.output stderr
```
