### ISSUE TITLE
Error starting node : Failed to unmount IPC

### ISSUE THREAD

**Issue by moon86** [storj/storj#3531] opened 2019-11-10 11:39 UTC
Hello,

I'm having an issue when I try to run my node. I'm getting the error failed to unmount IPC: unmount
The node is not starting, I reinstalled the storagenode and I'm getting some issues in the logs.
I'm using Ubuntu 16.04.

Here is the result of this command : 

> tail -f /var/log/syslog | grep docker 

`Nov 10 12:31:34 bob dockerd[1770]: time="2019-11-10T12:31:34.253016765+01:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Nov 10 12:31:34 bob kernel: [ 1958.189669] docker0: port 2(veth92a4eea) entered disabled state
Nov 10 12:31:34 bob kernel: [ 1958.240632] docker0: port 2(veth92a4eea) entered disabled state
Nov 10 12:31:34 bob kernel: [ 1958.243950] docker0: port 2(veth92a4eea) entered disabled state
Nov 10 12:31:34 bob dockerd[1770]: time="2019-11-10T12:31:34.423330341+01:00" level=warning msg="371a07acee469c0c7f7e7c0d18f15c25d524997ed63936298b8f84e7d9cbada0 cleanup: failed to unmount IPC: umount /var/lib/docker/containers/371a07acee469c0c7f7e7c0d18f15c25d524997ed63936298b8f84e7d9cbada0/mounts/shm, flags: 0x2: no such file or directory"`

Thanks in advance for your help.

**Comment by ifraixedes** [comment] 2019-11-12 14:12
It looks like a problem with your docker installation.

Can you try to run any other images with mounted volumes?

Also, please paste here the run command that you're using without sensitive data like wallet address.

**Comment by moon86** [comment] 2019-12-18 13:31
Hello, thank you for your response but what do you mean by "images with mounted volumes" ? Do you have an example ?

Here is the command that I run to launch the app :

`docker run -d --restart unless-stopped -p 28967:28967 -e WALLET="0x000000..." -e EMAIL="email@domain.com" -e ADDRESS="dns-name.com:28967" -e BANDWIDTH="20PB" -e STORAGE="2500GB" --mount type=bind,source="/home/user/.local/share/storj/identity/storagenode",destination=/app/identity --mount type=bind,source="/media/seagate/Storj",destination=/app/config --name storagenode storjlabs/storagenode:beta`

**Comment by ifraixedes** [comment] 2019-12-20 14:14
> what do you mean by "images with mounted volumes" ? Do you have an example ?

`docker run --rm -ti --mount type=bind,source="/home/user/.local/share/storj/identity/storagenode",destination=/app/identity --mount type=bind,source="/media/seagate/Storj",destination=/app/config ubuntu:18.04 /bin/bash`

You'll get into an interactive terminal inside the container and try to:

* `ls /app/identity`
* ls `/app/config`

**Comment by moon86** [comment] 2019-12-22 17:51
Here is the result of the commands : 

`user@bluelagoon:~$ docker run --rm -ti --mount type=bind,source="/home/user/.local/share/storj/identity/storagenode",destination=/app/identity --mount type=bind,source="/media/seagate/Storj",destination=/app/config ubuntu:16.04 /bin/bash
Unable to find image 'ubuntu:16.04' locally
16.04: Pulling from library/ubuntu
3386e6af03b0: Pull complete 
49ac0bbe6c8e: Pull complete 
d1983a67e104: Pull complete 
1a0f3a523f04: Pull complete 
Digest: sha256:181800dada370557133a502977d0e3f7abda0c25b9bbb035f199f5eb6082a114
Status: Downloaded newer image for ubuntu:16.04
root@e20e65da180f:/# ls /app/identity
ca.1234657980.cert  ca.cert  ca.key  identity.1234567890.cert  identity.cert  identity.key
root@e20e65da180f:/# ls /app/config
config.yaml  kademlia  revocations.db  storage`

**Comment by ifraixedes** [comment] 2019-12-30 13:04
Have you tried to run the `storagenode` container?

The problem looks that's in docker, I'd say that it's this one https://forums.docker.com/t/failed-to-unmount-ipc/86104 but unfortunately there isn't any answer.

**Comment by ifraixedes** [comment] 2020-01-29 17:16
I'm closing this assuming that you found the issue and fix it if that isn't the case, please comment and we'll reopen it.

**Closed by ifraixedes** 2020-01-29 17:16 UTC
Labels: Waiting for Feedback

**Comment by gutschet** [comment] 2020-03-04 13:56
We are also experiencing this bug:
```Mar  3 22:35:41 worker1 dockerd[2384]: time="2020-03-03T22:35:41.084377086+01:00" level=warning msg="8d038fada0dab0862693cb29021414fff054d7a72eb3f211f8c8eedd7f77cbce cleanup: failed to unmount IPC: umount /var/lib/docker/containers/8d038fada0dab0862693cb29021414fff054d7a72eb3f211f8c8eedd7f77cbce/mounts/shm, flags: 0x2: no such file or directory"```
We have mounted a tmpfs on /var/lib/docker/overlay2, /var/lib/docker/image, /var/lib/docker/containers. Could that be a cause for this problem?

**Comment by ifraixedes** [comment] 2020-03-04 16:42
> We have mounted a tmpfs on /var/lib/docker/overlay2, /var/lib/docker/image, /var/lib/docker/containers. 

Why do you need to do that?
What I can read in https://docs.docker.com/storage/tmpfs/ `tmpfs` doesn't map to any host directory, hence, are those paths inside of the container? can you sahre your docker run command?

> Could that be a cause for this problem?

Possible, can you try without the `tmpfs` mapping?

**Comment by gutschet** [comment] 2020-03-05 07:07
Maybe I did not explain clear enough. On our docker host, we have a tmpfs for the directories /var/lib/docker/overlay2, /var/lib/docker/image and /var/lib/docker/containers. We are doing this because we have worker hosts with very much RAM and only very small disks (SSD). Our workers are stateless, because all the persistent data is stored in volumes, that are located on a nfs share. Docker stores the filesystem layers of the images / containers under /var/lib/docker/overlay2 and some metadata under /var/lib/docker/image and /var/lib/docker/containers. Depending on the images / containers, that can be quite a lot of data and when starting and stopping different containers, there is also a lot of write activity, what is night,mare for the SSD disks. That is why we use the tmpfs. Besides it boosts performance.

**Comment by ifraixedes** [comment] 2020-03-05 16:07
Being honest, I don't know if that setup makes Docker fails to run containers.

What isn't to work is that the data directory of a storage node is in an NFS volume, but it shouldn't stop the container to run.

Is only storagenode image failing or whatever image?

**Comment by gutschet** [comment] 2020-03-06 07:16
In our case, we are doing test automation and what fails are browser node containers. But I am not sure if the error message in the log is really the cause of the failing containers. I will do some more tests today and check if the message always occurs, when my tests fail.

**Comment by sirsikar-lalit** [comment] 2020-04-01 17:46
I am getting these kind of messages in docker system daemon process:

`Apr 01 17:28:00 ip-10-8-0-90.us-west-1.compute.internal dockerd[6035]: time="2020-04-01T17:28:00.881593376Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Apr 01 17:28:00 ip-10-8-0-90.us-west-1.compute.internal dockerd[6035]: time="2020-04-01T17:28:00.881723898Z" level=warning msg="82d46bc22a12b910108cf84a0498b38380487a83966a6aa8449e1899bd982d4c cleanup: failed to unmount IPC: umount /awss3archieve/docker/containers/82d46bc22a12b910108cf84a0498b38380487a83966a6aa8449e1899bd982d4c/mounts/shm, flags: 0x2: no such file or directory"
Apr 01 17:28:08 ip-10-8-0-90.us-west-1.compute.internal dockerd[6035]: time="2020-04-01T17:28:08.080138023Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Apr 01 17:28:08 ip-10-8-0-90.us-west-1.compute.internal dockerd[6035]: time="2020-04-01T17:28:08.080313745Z" level=warning msg="dfb6586dca0aa154064cd7e3d066a88160a58ba3def712ac6306f424a746f231 cleanup: failed to unmount IPC: umount /awss3archieve/docker/containers/dfb6586dca0aa154064cd7e3d066a88160a58ba3def712ac6306f424a746f231/mounts/shm, flags: 0x2: no such file or directory"
Apr 01 17:30:23 ip-10-8-0-90.us-west-1.compute.internal dockerd[6035]: time="2020-04-01T17:30:23.875585111Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Apr 01 17:30:23 ip-10-8-0-90.us-west-1.compute.internal dockerd[6035]: time="2020-04-01T17:30:23.875711753Z" level=warning msg="a697d160a4aeaa438dcd326203762749326b54dea7fd962321b60ce688ad8dbb cleanup: failed to unmount IPC: umount /awss3archieve/docker/containers/a697d160a4aeaa438dcd326203762749326b54dea7fd962321b60ce688ad8dbb/mounts/shm, flags: 0x2: no such file or directory"
Apr 01 17:32:00 ip-10-8-0-90.us-west-1.compute.internal dockerd[6035]: time="2020-04-01T17:32:00.118202235Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Apr 01 17:32:00 ip-10-8-0-90.us-west-1.compute.internal dockerd[6035]: time="2020-04-01T17:32:00.118354877Z" level=warning msg="2d5b0fba100fd4ed508e4739018d272568d82ae8cc3d16015b7760cebd8f50bc cleanup: failed to unmount IPC: umount /awss3archieve/docker/containers/2d5b0fba100fd4ed508e4739018d272568d82ae8cc3d16015b7760cebd8f50bc/mounts/shm, flags: 0x2: no such file or directory"
Apr 01 17:33:10 ip-10-8-0-90.us-west-1.compute.internal dockerd[6035]: time="2020-04-01T17:33:10.834819500Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Apr 01 17:33:10 ip-10-8-0-90.us-west-1.compute.internal dockerd[6035]: time="2020-04-01T17:33:10.835088193Z" level=warning msg="d29ce55dd513470f717198a3d618a95d2d66165834576b04964d1035fe640abb cleanup: failed to unmount IPC: umount /awss3archieve/docker/containers/d29ce55dd513470f717198a3d618a95d2d66165834576b04964d1035fe640abb/mounts/shm, flags: 0x2: no such file or directory"`

Any resolutions? Is it safe to delete such docker containers from `docker ps` or directly from docker/containers path?

**Comment by xZero707** [comment] 2020-04-23 08:39
Same for **Docker version 19.03.4-rc1, build 4ba2b1c606**. 
docker run ... hangs for some specific images (not all).
When that occurs, these messages appear in the log.

So far I was able to reproduce it for **nginx:mainline-alpine**

**Comment by saurabhcdt** [comment] 2021-01-20 12:56
Is there a solution to this issue? I'm facing the same issue.
 Docker Version: 19.03.3
 Storage Driver: overlay2

Error:

Jan 20 12:32:34 devap01 dockerd[1129]: time="2021-01-20T12:32:34.901298354Z" level=error msg="fatal task error" error="starting container failed: OCI runtime create failed: container_linux.go:345: starting container process caused \"process_linux.go:430: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/var/app/docker/mounts/dev/myapi/log\\\\\\\" to rootfs \\\\\\\"/var/app/docker/storage/200000.200000/overlay2/014407a61744fa9bde29392155b44ca3b063fca28fb14faff39e392706184de6/merged\\\\\\\" at \\\\\\\"/app/myapi/log\\\\\\\" caused \\\\\\\"stat /var/app/docker/mounts/dev/myapi/log: permission denied\\\\\\\"\\\"\": unknown" module=node/agent/taskmanager node.id=et23kicrq9g1xx878g7o0ryi0 service.id=ddba3atxxmr5nw8cqjdjrf20n task.id=xbjknzmtnb6ivrop09mhri9gp

This happens when I try to deploy a new service. Other existing services run fine. My docker compose stack file for this service:
myapi:
    image: myregistry/myapi:0.0.1-1
    environment:
      LOGGING.FILE.NAME: /app/myapi/log/server.log
    volumes:
      - /var/app/docker/mounts/dev/myapi/log:/app/myapi/log
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.labels.myapi == true
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    stop_grace_period: 4m

**Comment by calebcase** [comment] 2021-01-21 19:56
@saurabhcdt This looks like a different problem from the original report. From the looks of your error message this is a permissions issue similar to https://github.com/docker/compose/issues/4039#issuecomment-269558432 There appear to be several ways this could occur and since the docker compose issue is fairly old I'm not sure which ones are relevant. I would check if your user is in the docker group (or running the docker compose command as root) and look at the order of your flags in case it is like the problem here https://github.com/docker/compose/issues/4039#issuecomment-278418458.
