### ISSUE TITLE
Node dashboard reports incorrect minimal version

### ISSUE THREAD

**Issue by jcassette** [storj/storj#5673] opened 2023-03-13 22:08 UTC
**Description**

The node dashboard reports the minimal allowed version is 1.24.0
https://version.storj.io/ reports the minimal allowed version is 1.73.4

**Screenshots**

![image](https://user-images.githubusercontent.com/7935799/224841993-cf652f2a-9cb0-4413-8746-dc600099b74b.png)

![image](https://user-images.githubusercontent.com/7935799/224842116-3e323941-9ecf-4020-b496-716548e8e7b4.png)

**Steps to reproduce the issue:**

1. Open the node dashboard

**Describe the results you expected:**
Minimal allowed version equal to 1.73.4

**Describe the results you received:**
Minimal allowed version equal to 1.24.0

**Additional information you deem important (e.g. issue happens only occasionally):**
Affected version: 1.73.4

**Your environment**

- Operating system and version: FreeBSD 13.1-RELEASE-p7 n245418-79e75956dbb TRUENAS amd64
- Additional environment details (Raspberry PI, Docker, VMWare, etc.):

**Comment by profclems** [comment] 2023-03-13 22:15
Duplicate of https://github.com/storj/storj/issues/4261. 

The version shown in the tooltip is the minimum node software version required to be able to run a node, not the node’s version. The tooltip is meant to convey the message that your node is running a version in the required version range.

**Comment by MaxMaximus** [comment] 2023-05-07 19:46
There are at lest two "minimal versions" to run on the Storj network.
1 - absolute minimum to run: nodes running versions below will be "kicked out" from network completely (other nodes will not accept connections and satellite will DQ it). This one is shown on the SNO Dashboard (and stick to v 1.24 for about 2 years already)
2 - minimum version counted as fully operational: nodes running versions below still accepted in the network but counted as outdated/second grade. For example they excluded from receiving ingress traffic and some of egress (end users usage) too. Only serve repair traffic and audits. This can be found in https://version.storj.io/ and it updates quite often - usually only one or two versions back from the latest release.

Latest should be included in SNO dashboard too. Because current situation is very confusing for a SNO. It see - i am running not the latest release (it doesn't matter for what reason) but above the minimum allowed by the network? So I don't really need to upgrade, I can continue using the current version without negative consequences. However, this is not true, because restrictions on the operation of the node by the network are imposed much earlier. And when exactly - it is not displayed anywhere in the control panel.

**Comment by profclems** [comment] 2023-11-06 14:50
Reopening this issue since we found out that it is bug because the version checker reads the minimum from the deprecated part https://storj.slack.com/archives/C047KSGPPQ8/p1698269747804149

**Comment by iglesiasbrandon** [comment] 2024-01-11 21:54
@profclems it looks like this fix has been deployed in production. I am going to close this issue. @shaupt131

**Closed by iglesiasbrandon** 2024-01-11 21:54 UTC
Labels: Bug
