### ISSUE TITLE
Piecestore error

### ISSUE THREAD

**Issue by erosfabbri24** [storj/storj#1949] opened 2019-05-11 23:18 UTC
i get this error everytime the node tries to download data

piecestore      download failed {"Piece ID": "Z2S3ODQ6ZBI5PV6OKJJKZXIKPFTB2BMHXSNZGDEYJY6XUQLKRMVQ", "error": "piecestore internal: pieces error: filestore error: unable to open \"config/storage/blob/abforhuxbzyd35blusvrifvdwmfx4hmocsva4vmpp3rgqaaaaaaa/z2/s3odq6zbi5pv6okjjkzxikpftb2bmhxsnzgdeyjy6xuqlkrmvq\": open config/storage/blob/abforhuxbzyd35blusvrifvdwmfx4hmocsva4vmpp3rgqaaaaaaa/z2/s3odq6zbi5pv6okjjkzxikpftb2bmhxsnzgdeyjy6xuqlkrmvq: no such file or directory", "errorVerbose": "piecestore internal: pieces error: filestore error: unable to open \"config/storage/blob/abforhuxbzyd35blusvrifvdwmfx4hmocsva4vmpp3rgqaaaaaaa/z2/s3odq6zbi5pv6okjjkzxikpftb2bmhxsnzgdeyjy6xuqlkrmvq\": open config/storage/blob/abforhuxbzyd35blusvrifvdwmfx4hmocsva4vmpp3rgqaaaaaaa/z2/s3odq6zbi5pv6okjjkzxikpftb2bmhxsnzgdeyjy6xuqlkrmvq: no such file or directory\n\tstorj.io/storj/storage/filestore.(*Dir).Open:152\n\tstorj.io/storj/storage/filestore.(*Store).Open:44\n\tstorj.io/storj/storagenode/pieces.(*Store).Reader:94\n\tstorj.io/storj/storagenode/piecestore.(*Endpoint).Download:336\n\tstorj.io/storj/pkg/pb._Piecestore_Download_Handler:628\n\tstorj.io/storj/pkg/server.streamInterceptor:19\n\tgoogle.golang.org/grpc.(*Server).processStreamingRPC:1182\n\tgoogle.golang.org/grpc.(*Server).handleStream:1254\n\tgoogle.golang.org/grpc.(*Server).serveStreams.func1.1:690"}

 piecestore internal: pieces error: filestore error: unable to open "config/storage/blob/abforhuxbzyd35blusvrifvdwmfx4hmocsva4vmpp3rgqaaaaaaa/z2/s3odq6zbi5pv6okjjkzxikpftb2bmhxsnzgdeyjy6xuqlkrmvq": open config/storage/blob/abforhuxbzyd35blusvrifvdwmfx4hmocsva4vmpp3rgqaaaaaaa/z2/s3odq6zbi5pv6okjjkzxikpftb2bmhxsnzgdeyjy6xuqlkrmvq: no such file or directory
        storj.io/storj/storage/filestore.(*Dir).Open:152
        storj.io/storj/storage/filestore.(*Store).Open:44
        storj.io/storj/storagenode/pieces.(*Store).Reader:94
        storj.io/storj/storagenode/piecestore.(*Endpoint).Download:336
        storj.io/storj/pkg/pb._Piecestore_Download_Handler:628
        storj.io/storj/pkg/server.streamInterceptor:19
        google.golang.org/grpc.(*Server).processStreamingRPC:1182
        google.golang.org/grpc.(*Server).handleStream:1254
        google.golang.org/grpc.(*Server).serveStreams.func1.1:690

**Comment by ReneSmeekes** [comment] 2019-05-14 11:06
Looks like you've lost data from your data folder. Please make sure the data folder is still mapped correctly. If you use an external disk, ensure that the mount point hasn't changed. For quicker support, please join #storagenode at https://community.storj.io .

**Comment by erosfabbri24** [comment] 2019-05-15 21:32
I requested the account activation on community.storj.io meanwhile i give you some additional informations. I'm using an internal hdd (the same i use for OS), i'm using ubuntu 16.04 and the error is shown often but not on every GET/PUT action.
@ReneSmeekes

**Comment by riegaz** [comment] 2019-05-18 20:04
I got the same error. I can confirm that the mount point is still valid and it is writable.

I requested an community account as well. No answer since about 2 weeks.

**Comment by heunland** [comment] 2019-05-18 20:19
@riegaz please contact us at support@storj.io if you still cannot login to rocket.chat and/or did not get an verification email. We need to manually verify each account after they confirm the verification email. Sorry for the delay!

**Comment by erosfabbri24** [comment] 2019-05-19 09:50
@riegaz if you get any helpful  answer , please write it bere

**Comment by erosfabbri24** [comment] 2019-05-19 09:50
Here*

**Comment by stefanbenten** [comment] 2019-07-05 18:30
@erosfabbri24 Is this error still occuring on your node?
If not, please close this issue as soon as possible.
Thank you!

**Closed** 2019-07-05 19:52 UTC
Labels: Waiting for Feedback
