### ISSUE TITLE
File browser: On mobile device, can't access menu in certain situations and billing should be under account in mobile view

### ISSUE THREAD

**Issue by nadimhq** [storj/storj#5153] opened 2022-09-07 14:50 UTC
**Description**
Preface, by saying hard refresh fixes the menu being missing but otherwise...hamburger menu dropdown should always appear on header but does not following these steps + billing should also be under account in mobile view according to our figma design but it is not in mobile view

**Environment**
Device: iPhone (also tested on simulated mobile screen (minimizing browser to mobile device specs)
Browsers: Chrome and Safari

**Steps to Reproduce**
1. Chrome Browser- first time logging in mobile (not simulated), without any cookies or site data, you end up on dashboard page without any way to access the menu need to refresh to see said hamburger, session timer shows up but its halfway cut off
2. Both Chrome and Safari- mobile view on phone(not simulated), one goes into bucket list and then opens said bucket with encryption passphrase, menu doesn’t show up and need to refresh menu to see said hamburger menu, session timer doesn’t show up as well
3. Both Chrome and Safari- mobile view simulated or not, billing is listed along with dashboard, buckets, access, users etc- according to figma design this should not be the case

**Results**
As stated before, **expected** to see the hamburger icon for menu access after following these steps and billing should be under my account, but **actually** there was no said icon and there was no way to navigate unless page was hard refreshed + billing was not listed under my account but instead listed above resources and under Users

https://user-images.githubusercontent.com/82845192/188906957-822de24c-3826-47f1-ae50-bd6329a51a43.mp4

![Capture (1)](https://user-images.githubusercontent.com/82845192/188908686-9198161f-e8ab-4679-9640-efc7f3e06919.JPG)

**Comment by xaresys** [comment] 2022-11-02 13:49
@nadimhq I am unable to reproduce the hamburger menu issue locally due to lacking an iOS device to do so. The site appears as expected on my Android device. Could you confirm whether this issue is still present?

**Comment by mobyvb** [comment] 2022-11-22 15:10
cc @wilfred-asomanii

**Comment by jewharton** [comment] 2022-11-29 15:46
The commit storj/storj@fe3aede that moves the mobile Billing navigation item into the My Account dropdown was deployed in v1.66. The issue with the mobile header not appearing is being addressed by @wilfred-asomanii.

**Comment by mobyvb** [comment] 2022-12-15 18:59
deployed in 1.69 https://github.com/storj/storj/commit/91b551134d807d06ff07f54d10fe381506f72f13

**Closed by mobyvb** 2022-12-15 18:59 UTC
Labels: Bug, Satellite UI
