### ISSUE TITLE
Newbie Trying to Setup a Node

### ISSUE THREAD

**Issue by leamur247** [storj/storj#1855] opened 2019-04-28 04:13 UTC
Where Have i gone wrong!?

le******@CPURig-T620:~$ sudo docker run -d --restart unless-stopped -p 28967:28967 \ 
-e WALLET="0x******************************************3D" \ 
-e EMAIL="kl*****@dyn******.com" \ 
-e ADDRESS="n************.hopto.org:28967" \ 
-e BANDWIDTH="500GB" \ 
-e STORAGE="500GB" \ 
-v "file:///home/le******/.local/share/storj/identity/":/app/identity \ 
-v "storjT620-1":/app/config \ 
--name storagenode storjlabs/storagenode:alpha

****docker: invalid reference format.
See 'docker run --help'.****

**Comment by stefanbenten** [comment] 2019-04-28 05:24
Hello @leamur247,

your paths that you want to mount are looking wrong.
Please try it with the following string:

```udo docker run -d --restart unless-stopped -p 28967:28967 \
-e WALLET="0x*************3D" \
-e EMAIL="kl@DYN.com" \
-e ADDRESS="n.hopto.org:28967" \
-e BANDWIDTH="500GB" \
-e STORAGE="500GB" \
-v /home/le/.local/share/storj/identity/:/app/identity \
-v /path/to/storage/:/app/config \
--name storagenode storjlabs/storagenode:alpha```

In the above example you have to replace /path/to/storage/ to a location on your drive, that has your specified space of 500GB available.
Hope that helps!

**Comment by leamur247** [comment] 2019-04-28 05:30
-v /home/leamur247/.local/share/storj/identity/:/app/identity \ 
-v /media/storjT620-1/:/app/config \ 
--name storagenode storjlabs/storagenode:alpha

docker: invalid reference format.
See 'docker run --help'.

See updated sections above.  Still getting error.

Thanks so much for your help!!!!

**Comment by ReneSmeekes** [comment] 2019-04-28 14:59
Try it like this:

```
sudo docker run -d --restart unless-stopped -p 28967:28967 \
-e WALLET="0x*************3D" \
-e EMAIL="kl@DYN.com" \
-e ADDRESS="n.hopto.org:28967" \
-e BANDWIDTH="500GB" \
-e STORAGE="500GB" \
-v "/home/leamur247/.local/share/storj/identity":/app/identity \
-v "/media/storjT620-1":/app/config \
--name storagenode storjlabs/storagenode:alpha
```
I think it might be tripping up over the - in the path otherwise. For more immediate help/response you can also ask in #storagenode on community.storj.io if this didn't work.

**Comment by iglesiasbrandon** [comment] 2019-05-07 12:36
@leamur247 were you able to get your Storj Node up and running? Please let us know if you are still having any issues.

**Comment by leamur247** [comment] 2019-05-17 03:24
![Screenshot from 2019-05-16 23-23-10](https://user-images.githubusercontent.com/38448743/57901123-af392800-7831-11e9-8929-0b69b8d00b3f.png)

Same issue even with the edits.  However, I did run the logs and got this info.  Any clue on what I might try next?

**Comment by ReneSmeekes** [comment] 2019-05-17 04:45
It looks like you don't have the correct permissions to run the logs command as your current user. You can solve that by adding the user to the docker group or using sudo in front of the command.

As for what is going wrong with the run command, that's hard to say, since you're not showing the command you used in the screenshot.

**Comment by kaloyan-raev** [comment] 2019-06-26 07:21
I am closing this issue due to no new response from the author from more than a month. If the issue is still valid, please reopen and provide additional info.

**Closed by kaloyan-raev** 2019-06-26 07:21 UTC
Labels: Waiting for Feedback
