### ISSUE TITLE
Disk access conflict if Storj folder accesed by other software on windows

### ISSUE THREAD

**Issue by MaxMaximus** [storj/storj#3919] opened 2020-07-08 01:40 UTC
Hello.

Today i encounter (and been able to reproduce) strange bug with storage node:
If i open a "temp" folder (i think it apply to  other folder where storj is currently writing too, but i tested with "temp") during active upload to node explorer can not open it and stops responding. It looks much like a disk errors/connection issues on failing disk, but disk itself working OK and explorer can open any other folders on same disk which not used by Storj. Also can open same "temp" folder of Storj not currently running.
At the same time storj node stops writing to disk too and all incoming uploads pile up in the RAM after that moment (RAM usage begin to grow fast). 
Also in the logs at same time only a lot of "upload started" entries (i testes during active upload period - about 15-30 Mbit/s of ingress traffic) but not a single one entry with "uploaded" or "upload canceled". Although download requests seems to be processed OK - some "download started" and "downloaded" or "download canceled".

It can stay "stuck" like this for a really long periods of time. One try i waited for about 10-15 minutes and explorer still not responding and storj still did not write any pieces to disk. RAM usage grows from 50 MB to ~2000 MB during test and i shut it down to avoid crash due to out а RAM errors.

If i send stop command to node - TONS of "upload canceled" entries begin to pop-up in log, RAM usage begin to decrease fast and after some time node shut down correctly. 
Right at the moment of node shutdown windows explorer "unfreeze" and open folder normally.

Strange disk access conflict which blocks explorer reading from disk and blocks storj writing to disk at same time.

SN ver 1.6.4 GUI (service) on Window x64
Example log during one of "jams":
[NOwrites.txt](https://github.com/storj/storj/files/4887888/NOwrites.txt)

At 2020-07-08T03:42:32.381 i sent shutdown command to node and all stuck uploads were canceled in one row and disk access "unlocked" after it.

**Comment by egonelbre** [comment] 2020-07-08 08:57
Do you have any anti-virus software installed? Programs that do active scanning on a folder can conflict with them.

**Comment by egonelbre** [comment] 2020-07-09 13:55
I did try reproducing locally with network simulation, but it seems to be working.

**Comment by stefanbenten** [comment] 2020-12-04 18:51
@MaxMaximus Can you please give an update on this issue?
Else we will be closing this soon, as unable to get a reproducer.

**Comment by MaxMaximus** [comment] 2020-12-07 23:17
Yes. It was not related to anti-virus SW, it repeated few times with any disk scan SW removed (not just disabled, but after complete uninstall and computer reboot)    
But i did not see any such problems in few latest versions in last 2-3 month. its gone after one of Storj Node SW updates.
So I think the problem can be considered resolved.

**Closed** 2020-12-07 23:34 UTC
Labels: Need investigation, Waiting for Feedback
