### ISSUE TITLE
Account Deletion: Handling Billing

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#7050] opened 2024-07-10 16:27 UTC
### Summary
We need to handle partial billing for when users decide to delete their accounts. In almost all scenarios there will be some amount of usage incurred that has not yet been billed at the time of deletion.

### Acceptance Criteria
- A user should only be able to trigger self serve account deletion if ALL existing invoices are paid
- We should stop charging for use after this day
- Invoice should be still generated for the partial month usage and sent to the email of the account holder
- Actual deletion of the account shouldn't happen until invoice has been paid

Note that if it is A LOT of effort to figure out how to charge for the partial month usage, that may be fine: https://storj.slack.com/archives/C0490040EDR/p1720193017762489?thread_ts=1720024584.026139&cid=C0490040EDR

**Comment by ferristocrat** [comment] 2024-07-10 16:28
@boshevski - any thoughts on the above? I think at a minimum we should  have a design for "pay all your outstanding invoices before you can delete" scenario

**Comment by heunland** [comment] 2024-07-10 16:51
I hope you are also considering the not yet billed usage up to the time the customer files the deletion request as also outstanding. Please read my comment right below the one from @dorrie55 in the slack thread @ferristocrat linked above and which she agreed to. I.e. we should bill them and collect payment for partial month usage before letting them self serve delete the account. We will have a lot of lost revenue otherwise, as the great majority of the Pro Account users do pay their last partial month usage up to data deletion now when we do the account deletions manually. Dorrie in her comment was referring to the cases where we were having to force delete accounts that were billing frozen, and where the users refused to pay, not the regular deletion requests we now receive via Zendesk ticket and that prod owners manually process now.

Of those that file regular account deletion requests, hardly anyone even complains about having to wait until the regular invoicing that happens the next month before their account actually gets deleted. I.e. if it is a lot of effort to code creation of invoices for the partial month, I propose that we could have a first version where the user just sees a notification that their data has already been deleted from the account so they are no longer incurring more charges for the rest of the month, but we will wait with the final account deletion until after the next normal invoicing is done.

**Comment by ferristocrat** [comment] 2024-07-11 18:24
Thanks @heunland - @boshevski is iterating on design to incorporate what you emphasize above - specifically handling the current month usage. Once we settle on the design we can review to make sure it makes sense and make any trade offs needed based on engineering complexity. I think the simplest solution to your point is something along the lines of make sure that they won't incur usage point forward and send them the last invoice when it gets generated at period end

**Comment by ferristocrat** [comment] 2024-07-11 18:24
Let's hold off sizing/working on this until we have final design from @boshevski

**Comment by boshevski** [comment] 2024-07-16 16:26
Design no.1: All invoices paid.
<img width="494" alt="delete-invoices-paid" src="https://github.com/user-attachments/assets/c15a0451-488f-46ac-a8d0-094c0bf0b287">
In case where all invoices are paid, we can estimate the amount for the current billing period, and send the invoice on email.

**Comment by boshevski** [comment] 2024-07-16 16:29
Design no.1: Unpaid invoices.
<img width="473" alt="delete-unpaid-invoices" src="https://github.com/user-attachments/assets/b9618589-8081-4a01-8d59-7cb0855b7df0">
If there are unpaid invoices we can direct users to the billing page to pay the invoices.

**Comment by boshevski** [comment] 2024-07-16 16:30
We can look at Stripe Checkout to implement for paying invoices and/or current month's estimated usage.
https://stripe.com/payments/checkout
https://checkout.stripe.dev/preview
https://docs.stripe.com/payments/checkout
Invoice by email can also be paid using Stripe.

**Comment by NiaStorj** [comment] 2024-07-24 14:20
closing as a duplicate of https://github.com/storj/storj/issues/7069

**Closed by NiaStorj** 2024-07-24 14:20 UTC
Labels: Needs Estimation, Needs Grooming
