### ISSUE TITLE
File editing not working on uplink mounted bucket

### ISSUE THREAD

**Issue by Luca8991** [storj/storj#1288] opened 2019-02-10 20:27 UTC
I mounted the **bucket** I created in the _storj-sim network_ via:
```bash
uplink --config-dir .local/share/storj/local-network/gateway/0/ mount s3://test /home/<me>/storj-mtest
```
It works as I see the files and can copy in or out the mounted folder.
But I can't **edit** or **rename** the files within that.
I also have problems when trying to read a _.avi_ file with VLC.

The _storj-sim network_ is configured as default. 
The gateway used by _uplink_ is the default gateway of the _storj-sim network_.

Here are my OS specs:
```bash
Ubuntu 18.04.1 LTS
Linux 4.15.0-45-generic
x86_64
```

**Comment by mniewrzal** [comment] 2019-02-10 20:45
Hi @Luca8991 
Currently *mount* command doesn't support all possible OS operations. You can copy file from and to the bucket but things like renaming file or editing existing file doesn't work yet.
File streaming should work fine but its possible that you found a problem to fix. Can you share a link to your file? Or can you try sample movie e.g. https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_10mb.mp4?

**Comment by Luca8991** [comment] 2019-02-10 21:14
The playback of the bunny video only stopped one time (using VLC)

**Comment by Luca8991** [comment] 2019-02-10 21:32
My _.avi_ file weights 169MB and VLC playback stops every 3 secs (43 secs tot).
The _bunny video_'s playback on VLC is great and fluid, without stops (also when jumping).

**Comment by stefanbenten** [comment] 2019-02-10 21:43
@Luca8991 Could it be that your machine was bottlenecked by either CPU, RAM or Disk IO?
That sounds like it

**Comment by Luca8991** [comment] 2019-02-10 22:13
@stefanbenten I don't think it's like you suggest... Otherwise, how can I check it?

**Comment by stefanbenten** [comment] 2019-02-10 22:21
Try the same movie again and watch the resource monitors, like `htop` and `iostat -x 2`. The former is for CPU and RAM usage, the later for disk IO. You might have to install them.

**Comment by Luca8991** [comment] 2019-02-11 11:02
Disk IO does not seem to be bottlenecked (%usage up to 98).
Also CPU and RAM seem to run at the maximum available

**Comment by mniewrzal** [comment] 2019-02-11 11:17
Can you paste your avi file code info? In VLC it will be in Tools -> Codec Information

**Comment by Luca8991** [comment] 2019-02-11 11:36
Here we are
![screenshot-codec-video-vlc](https://user-images.githubusercontent.com/12596698/52560725-88fe8900-2df9-11e9-8760-b29c68ea7284.png)

**Comment by mniewrzal** [comment] 2019-02-11 15:19
I tried several sample movies with similar encoding but unfortunately, I was not able to reproduce your issue.

**Comment by calebcase** [comment] 2019-11-24 16:59
@Luca8991 We are working on an rclone integration (https://github.com/rclone/rclone/pull/3699) that might serve you better. Rclone has a mount option (https://rclone.org/commands/rclone_mount/) and offers many other utilities as well (sync, rcd, purge, etc). It has the same limitations in terms of move and rename though as those operations aren't supported by Storj. But we have had good experiences copying files and streaming/seeking videos from a mount. If you try it out I'd be very interested in your experiences!

**Comment by calebcase** [comment] 2020-01-29 18:23
We are still working actively toward a mainline rclone integration. @Luca8991 I'm closing out the issue in favor of using the rclone integration. Thanks for reporting the original issue!

**Closed by calebcase** 2020-01-29 18:23 UTC
Labels: Bug
