### ISSUE TITLE
cmd/storagenode: rehaul forget-satellite command

### ISSUE THREAD

**Issue by profclems** [storj/storj#6541] opened 2023-11-21 19:04 UTC
This issue will outline the new behaviour we intend for the forget-satellite subcommand to fix the issue here https://github.com/storj/storj/issues/6465.

The current forget-satellite would only work when the storage node is completely shutdown while running the command. Although we require a restart, any service that uses the trust cache and updates the DB like the reputation cache might store data for the satellite, until the node is restarted.

We want to redesign the comand to work like the `exit-satellite` command for graceful exit which sends a drpc request to the main storagenode process to initiate graceful exit.

Old behaviour
- The forget-satellite command is run while the node is still running
- Forget-satellite has completed successfully
   - The main node process is not aware of the data cleanup done by the forget-satellite command
   - Disk used by the satellites cleaned up are still accounted for by the storagenode; https://github.com/storj/customer-issues/issues/1191
- The node is restarted
   - A new filewalker is initiated
   - Takes time from a few seconds to hours (depending on how large the node is for the filewalker to complete) before the cleaned up data is noticed
   - order service archives pending orders for untrusted satellites

Alternatively, if the node is shutdown before running the command and then restarted, we still have to wait for the next filewalker process to complete before the data clean up is noticed.

Proposed behaviour
- The `forget-satellite` command is run while the node is still running
- A drpc request is sent to the node to initiate data cleanup for the satellite
   - If node is offline, it should fall back to the old behaviour
- Node marks the satellite as untrusted in the satelliteDB, responds to the request and starts the data cleanup
- The command exits successfully indicating that the cleanup is in progress
- A new `forget-satellite-status` command to check the status of the clean up
- Satellite is marked as untrusted
- A new chore that checks for `untrusted` or `cleanup_in_progress` status in the satellite DB, and initiates cleanup so the clean up is continued even when the node is restarted at aby point

**Comment by egonelbre** [comment] 2023-11-21 19:11
> Although we require a restart, any service that uses the trust cache and updates the DB like the reputation cache might store data for the satellite, until the node is restarted.

Note the issue isn't just that they might store things in cache, they may reinsert the data into the DB that was removed.

**Comment by AlexeyALeonov** [comment] 2023-11-28 03:13
Restarting the node did not help to fix the API response, see https://github.com/storj/customer-issues/issues/1191

**Comment by iglesiasbrandon** [comment] 2024-02-27 14:08
moving to deployed.

**Closed by iglesiasbrandon** 2024-02-27 14:08 UTC
